// @generated by carcinize.nu from FMOD headers
/* ======================================================================================== */
/* FMOD Studio API - Common C/C++ header file.                                              */
/* Copyright (c), Firelight Technologies Pty, Ltd. 2004-2025.                               */
/*                                                                                          */
/* This header defines common enumerations, structs and callbacks that are shared between   */
/* the C and C++ interfaces.                                                                */
/*                                                                                          */
/* For more detail visit:                                                                   */
/* https://fmod.com/docs/2.03/api/studio-api.html                                           */
/* ======================================================================================== */

/*
    FMOD Studio types.
*/
pub type FMOD_STUDIO_SYSTEM           = self::_FMOD_STUDIO_SYSTEM          ::FMOD_STUDIO_SYSTEM          ; mod _FMOD_STUDIO_SYSTEM           { #[repr(C)] pub struct FMOD_STUDIO_SYSTEM           { _pin: ::core::marker::PhantomData<::core::marker::PhantomPinned>, _data: ::core::cell::UnsafeCell<[u8; 0]> } }
pub type FMOD_STUDIO_EVENTDESCRIPTION = self::_FMOD_STUDIO_EVENTDESCRIPTION::FMOD_STUDIO_EVENTDESCRIPTION; mod _FMOD_STUDIO_EVENTDESCRIPTION { #[repr(C)] pub struct FMOD_STUDIO_EVENTDESCRIPTION { _pin: ::core::marker::PhantomData<::core::marker::PhantomPinned>, _data: ::core::cell::UnsafeCell<[u8; 0]> } }
pub type FMOD_STUDIO_EVENTINSTANCE    = self::_FMOD_STUDIO_EVENTINSTANCE   ::FMOD_STUDIO_EVENTINSTANCE   ; mod _FMOD_STUDIO_EVENTINSTANCE    { #[repr(C)] pub struct FMOD_STUDIO_EVENTINSTANCE    { _pin: ::core::marker::PhantomData<::core::marker::PhantomPinned>, _data: ::core::cell::UnsafeCell<[u8; 0]> } }
pub type FMOD_STUDIO_BUS              = self::_FMOD_STUDIO_BUS             ::FMOD_STUDIO_BUS             ; mod _FMOD_STUDIO_BUS              { #[repr(C)] pub struct FMOD_STUDIO_BUS              { _pin: ::core::marker::PhantomData<::core::marker::PhantomPinned>, _data: ::core::cell::UnsafeCell<[u8; 0]> } }
pub type FMOD_STUDIO_VCA              = self::_FMOD_STUDIO_VCA             ::FMOD_STUDIO_VCA             ; mod _FMOD_STUDIO_VCA              { #[repr(C)] pub struct FMOD_STUDIO_VCA              { _pin: ::core::marker::PhantomData<::core::marker::PhantomPinned>, _data: ::core::cell::UnsafeCell<[u8; 0]> } }
pub type FMOD_STUDIO_BANK             = self::_FMOD_STUDIO_BANK            ::FMOD_STUDIO_BANK            ; mod _FMOD_STUDIO_BANK             { #[repr(C)] pub struct FMOD_STUDIO_BANK             { _pin: ::core::marker::PhantomData<::core::marker::PhantomPinned>, _data: ::core::cell::UnsafeCell<[u8; 0]> } }
pub type FMOD_STUDIO_COMMANDREPLAY    = self::_FMOD_STUDIO_COMMANDREPLAY   ::FMOD_STUDIO_COMMANDREPLAY   ; mod _FMOD_STUDIO_COMMANDREPLAY    { #[repr(C)] pub struct FMOD_STUDIO_COMMANDREPLAY    { _pin: ::core::marker::PhantomData<::core::marker::PhantomPinned>, _data: ::core::cell::UnsafeCell<[u8; 0]> } }

/*
    FMOD Studio constants
*/
pub const FMOD_STUDIO_LOAD_MEMORY_ALIGNMENT:                   ::core::ffi::c_int = 32;

pub const FMOD_STUDIO_INIT_NORMAL:                             FMOD_STUDIO_INITFLAGS = 0x00000000;
pub const FMOD_STUDIO_INIT_LIVEUPDATE:                         FMOD_STUDIO_INITFLAGS = 0x00000001;
pub const FMOD_STUDIO_INIT_ALLOW_MISSING_PLUGINS:              FMOD_STUDIO_INITFLAGS = 0x00000002;
pub const FMOD_STUDIO_INIT_SYNCHRONOUS_UPDATE:                 FMOD_STUDIO_INITFLAGS = 0x00000004;
pub const FMOD_STUDIO_INIT_DEFERRED_CALLBACKS:                 FMOD_STUDIO_INITFLAGS = 0x00000008;
pub const FMOD_STUDIO_INIT_LOAD_FROM_UPDATE:                   FMOD_STUDIO_INITFLAGS = 0x00000010;
pub const FMOD_STUDIO_INIT_MEMORY_TRACKING:                    FMOD_STUDIO_INITFLAGS = 0x00000020;
pub type FMOD_STUDIO_INITFLAGS = ::core::ffi::c_uint;

pub const FMOD_STUDIO_PARAMETER_READONLY:                      FMOD_STUDIO_PARAMETER_FLAGS = 0x00000001;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC:                     FMOD_STUDIO_PARAMETER_FLAGS = 0x00000002;
pub const FMOD_STUDIO_PARAMETER_GLOBAL:                        FMOD_STUDIO_PARAMETER_FLAGS = 0x00000004;
pub const FMOD_STUDIO_PARAMETER_DISCRETE:                      FMOD_STUDIO_PARAMETER_FLAGS = 0x00000008;
pub const FMOD_STUDIO_PARAMETER_LABELED:                       FMOD_STUDIO_PARAMETER_FLAGS = 0x00000010;
pub type FMOD_STUDIO_PARAMETER_FLAGS = ::core::ffi::c_uint;

pub const FMOD_STUDIO_SYSTEM_CALLBACK_PREUPDATE:               FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = 0x00000001;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_POSTUPDATE:              FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = 0x00000002;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_BANK_UNLOAD:             FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = 0x00000004;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_LIVEUPDATE_CONNECTED:    FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = 0x00000008;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_LIVEUPDATE_DISCONNECTED: FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = 0x00000010;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_ALL:                     FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = 0xFFFFFFFF;
pub type FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = ::core::ffi::c_uint;

pub const FMOD_STUDIO_EVENT_CALLBACK_CREATED:                  FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000001;
pub const FMOD_STUDIO_EVENT_CALLBACK_DESTROYED:                FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000002;
pub const FMOD_STUDIO_EVENT_CALLBACK_STARTING:                 FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000004;
pub const FMOD_STUDIO_EVENT_CALLBACK_STARTED:                  FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000008;
pub const FMOD_STUDIO_EVENT_CALLBACK_RESTARTED:                FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000010;
pub const FMOD_STUDIO_EVENT_CALLBACK_STOPPED:                  FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000020;
pub const FMOD_STUDIO_EVENT_CALLBACK_START_FAILED:             FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000040;
pub const FMOD_STUDIO_EVENT_CALLBACK_CREATE_PROGRAMMER_SOUND:  FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000080;
pub const FMOD_STUDIO_EVENT_CALLBACK_DESTROY_PROGRAMMER_SOUND: FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000100;
pub const FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_CREATED:           FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000200;
pub const FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_DESTROYED:         FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000400;
pub const FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_MARKER:          FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00000800;
pub const FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_BEAT:            FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00001000;
pub const FMOD_STUDIO_EVENT_CALLBACK_SOUND_PLAYED:             FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00002000;
pub const FMOD_STUDIO_EVENT_CALLBACK_SOUND_STOPPED:            FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00004000;
pub const FMOD_STUDIO_EVENT_CALLBACK_REAL_TO_VIRTUAL:          FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00008000;
pub const FMOD_STUDIO_EVENT_CALLBACK_VIRTUAL_TO_REAL:          FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00010000;
pub const FMOD_STUDIO_EVENT_CALLBACK_START_EVENT_COMMAND:      FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00020000;
pub const FMOD_STUDIO_EVENT_CALLBACK_NESTED_TIMELINE_BEAT:     FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0x00040000;
pub const FMOD_STUDIO_EVENT_CALLBACK_ALL:                      FMOD_STUDIO_EVENT_CALLBACK_TYPE = 0xFFFFFFFF;
pub type FMOD_STUDIO_EVENT_CALLBACK_TYPE = ::core::ffi::c_uint;

pub const FMOD_STUDIO_LOAD_BANK_NORMAL:                        FMOD_STUDIO_LOAD_BANK_FLAGS = 0x00000000;
pub const FMOD_STUDIO_LOAD_BANK_NONBLOCKING:                   FMOD_STUDIO_LOAD_BANK_FLAGS = 0x00000001;
pub const FMOD_STUDIO_LOAD_BANK_DECOMPRESS_SAMPLES:            FMOD_STUDIO_LOAD_BANK_FLAGS = 0x00000002;
pub const FMOD_STUDIO_LOAD_BANK_UNENCRYPTED:                   FMOD_STUDIO_LOAD_BANK_FLAGS = 0x00000004;
pub type FMOD_STUDIO_LOAD_BANK_FLAGS = ::core::ffi::c_uint;

pub const FMOD_STUDIO_COMMANDCAPTURE_NORMAL:                   FMOD_STUDIO_COMMANDCAPTURE_FLAGS = 0x00000000;
pub const FMOD_STUDIO_COMMANDCAPTURE_FILEFLUSH:                FMOD_STUDIO_COMMANDCAPTURE_FLAGS = 0x00000001;
pub const FMOD_STUDIO_COMMANDCAPTURE_SKIP_INITIAL_STATE:       FMOD_STUDIO_COMMANDCAPTURE_FLAGS = 0x00000002;
pub type FMOD_STUDIO_COMMANDCAPTURE_FLAGS = ::core::ffi::c_uint;

pub const FMOD_STUDIO_COMMANDREPLAY_NORMAL:                    FMOD_STUDIO_COMMANDREPLAY_FLAGS = 0x00000000;
pub const FMOD_STUDIO_COMMANDREPLAY_SKIP_CLEANUP:              FMOD_STUDIO_COMMANDREPLAY_FLAGS = 0x00000001;
pub const FMOD_STUDIO_COMMANDREPLAY_FAST_FORWARD:              FMOD_STUDIO_COMMANDREPLAY_FLAGS = 0x00000002;
pub const FMOD_STUDIO_COMMANDREPLAY_SKIP_BANK_LOAD:            FMOD_STUDIO_COMMANDREPLAY_FLAGS = 0x00000004;
pub type FMOD_STUDIO_COMMANDREPLAY_FLAGS = ::core::ffi::c_uint;

pub const FMOD_STUDIO_LOADING_STATE_UNLOADING: FMOD_STUDIO_LOADING_STATE = 0;
pub const FMOD_STUDIO_LOADING_STATE_UNLOADED: FMOD_STUDIO_LOADING_STATE = FMOD_STUDIO_LOADING_STATE_UNLOADING + 1;
pub const FMOD_STUDIO_LOADING_STATE_LOADING: FMOD_STUDIO_LOADING_STATE = FMOD_STUDIO_LOADING_STATE_UNLOADED + 1;
pub const FMOD_STUDIO_LOADING_STATE_LOADED: FMOD_STUDIO_LOADING_STATE = FMOD_STUDIO_LOADING_STATE_LOADING + 1;
pub const FMOD_STUDIO_LOADING_STATE_ERROR: FMOD_STUDIO_LOADING_STATE = FMOD_STUDIO_LOADING_STATE_LOADED + 1;
pub type FMOD_STUDIO_LOADING_STATE = ::core::ffi::c_int;

pub const FMOD_STUDIO_LOAD_MEMORY: FMOD_STUDIO_LOAD_MEMORY_MODE = 0;
pub const FMOD_STUDIO_LOAD_MEMORY_POINT: FMOD_STUDIO_LOAD_MEMORY_MODE = FMOD_STUDIO_LOAD_MEMORY + 1;
pub type FMOD_STUDIO_LOAD_MEMORY_MODE = ::core::ffi::c_int;

pub const FMOD_STUDIO_PARAMETER_GAME_CONTROLLED: FMOD_STUDIO_PARAMETER_TYPE = 0;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_GAME_CONTROLLED + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED_ABSOLUTE: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED + 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE_NORMALIZED: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED_ABSOLUTE + 1;

pub const FMOD_STUDIO_PARAMETER_MAX: FMOD_STUDIO_PARAMETER_TYPE = FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE_NORMALIZED + 1;
pub type FMOD_STUDIO_PARAMETER_TYPE = ::core::ffi::c_int;

pub const FMOD_STUDIO_USER_PROPERTY_TYPE_INTEGER: FMOD_STUDIO_USER_PROPERTY_TYPE = 0;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_BOOLEAN: FMOD_STUDIO_USER_PROPERTY_TYPE = FMOD_STUDIO_USER_PROPERTY_TYPE_INTEGER + 1;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_FLOAT: FMOD_STUDIO_USER_PROPERTY_TYPE = FMOD_STUDIO_USER_PROPERTY_TYPE_BOOLEAN + 1;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_STRING: FMOD_STUDIO_USER_PROPERTY_TYPE = FMOD_STUDIO_USER_PROPERTY_TYPE_FLOAT + 1;
pub type FMOD_STUDIO_USER_PROPERTY_TYPE = ::core::ffi::c_int;

pub const FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY: FMOD_STUDIO_EVENT_PROPERTY = 0;
pub const FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY: FMOD_STUDIO_EVENT_PROPERTY = FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY + 1;
pub const FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD: FMOD_STUDIO_EVENT_PROPERTY = FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY + 1;
pub const FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE: FMOD_STUDIO_EVENT_PROPERTY = FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD + 1;
pub const FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE: FMOD_STUDIO_EVENT_PROPERTY = FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE + 1;
pub const FMOD_STUDIO_EVENT_PROPERTY_COOLDOWN: FMOD_STUDIO_EVENT_PROPERTY = FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE + 1;
pub const FMOD_STUDIO_EVENT_PROPERTY_MAX: FMOD_STUDIO_EVENT_PROPERTY = FMOD_STUDIO_EVENT_PROPERTY_COOLDOWN + 1;
pub type FMOD_STUDIO_EVENT_PROPERTY = ::core::ffi::c_int;

pub const FMOD_STUDIO_PLAYBACK_PLAYING: FMOD_STUDIO_PLAYBACK_STATE = 0;
pub const FMOD_STUDIO_PLAYBACK_SUSTAINING: FMOD_STUDIO_PLAYBACK_STATE = FMOD_STUDIO_PLAYBACK_PLAYING + 1;
pub const FMOD_STUDIO_PLAYBACK_STOPPED: FMOD_STUDIO_PLAYBACK_STATE = FMOD_STUDIO_PLAYBACK_SUSTAINING + 1;
pub const FMOD_STUDIO_PLAYBACK_STARTING: FMOD_STUDIO_PLAYBACK_STATE = FMOD_STUDIO_PLAYBACK_STOPPED + 1;
pub const FMOD_STUDIO_PLAYBACK_STOPPING: FMOD_STUDIO_PLAYBACK_STATE = FMOD_STUDIO_PLAYBACK_STARTING + 1;
pub type FMOD_STUDIO_PLAYBACK_STATE = ::core::ffi::c_int;

pub const FMOD_STUDIO_STOP_ALLOWFADEOUT: FMOD_STUDIO_STOP_MODE = 0;
pub const FMOD_STUDIO_STOP_IMMEDIATE: FMOD_STUDIO_STOP_MODE = FMOD_STUDIO_STOP_ALLOWFADEOUT + 1;
pub type FMOD_STUDIO_STOP_MODE = ::core::ffi::c_int;

pub const FMOD_STUDIO_INSTANCETYPE_NONE: FMOD_STUDIO_INSTANCETYPE = 0;
pub const FMOD_STUDIO_INSTANCETYPE_SYSTEM: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_NONE + 1;
pub const FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_SYSTEM + 1;
pub const FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION + 1;
pub const FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE + 1;
pub const FMOD_STUDIO_INSTANCETYPE_BUS: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE + 1;
pub const FMOD_STUDIO_INSTANCETYPE_VCA: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_BUS + 1;
pub const FMOD_STUDIO_INSTANCETYPE_BANK: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_VCA + 1;
pub const FMOD_STUDIO_INSTANCETYPE_COMMANDREPLAY: FMOD_STUDIO_INSTANCETYPE = FMOD_STUDIO_INSTANCETYPE_BANK + 1;
pub type FMOD_STUDIO_INSTANCETYPE = ::core::ffi::c_int;

/*
    FMOD Studio structures
*/
#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_BANK_INFO {
    pub size: ::core::ffi::c_int,
    pub userdata: *mut ::core::ffi::c_void,
    pub userdatalength: ::core::ffi::c_int,
    pub opencallback: FMOD_FILE_OPEN_CALLBACK,
    pub closecallback: FMOD_FILE_CLOSE_CALLBACK,
    pub readcallback: FMOD_FILE_READ_CALLBACK,
    pub seekcallback: FMOD_FILE_SEEK_CALLBACK,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_PARAMETER_ID {
    pub data1: ::core::ffi::c_uint,
    pub data2: ::core::ffi::c_uint,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_PARAMETER_DESCRIPTION {
    pub name: *const ::core::ffi::c_char,
    pub id: FMOD_STUDIO_PARAMETER_ID,
    pub minimum: ::core::ffi::c_float,
    pub maximum: ::core::ffi::c_float,
    pub defaultvalue: ::core::ffi::c_float,
    pub r#type: FMOD_STUDIO_PARAMETER_TYPE,
    pub flags: FMOD_STUDIO_PARAMETER_FLAGS,
    pub guid: FMOD_GUID,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_USER_PROPERTY {
    pub name: *const ::core::ffi::c_char,
    pub r#type: FMOD_STUDIO_USER_PROPERTY_TYPE,
    pub value: FMOD_STUDIO_USER_PROPERTY_VALUE,
}

#[repr(C)] #[derive(Copy, Clone)] pub union FMOD_STUDIO_USER_PROPERTY_VALUE {
    pub intvalue: ::core::ffi::c_int,
    pub boolvalue: FMOD_BOOL,
    pub floatvalue: ::core::ffi::c_int,
    pub stringvalue: *const ::core::ffi::c_char,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES {
    pub name: *const ::core::ffi::c_char,
    pub sound: *mut FMOD_SOUND,
    pub subsoundIndex: ::core::ffi::c_int,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES {
    pub name: *const ::core::ffi::c_char,
    pub dsp: *mut FMOD_DSP,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES {
    pub name: *const ::core::ffi::c_char,
    pub position: ::core::ffi::c_int,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES {
    pub bar: ::core::ffi::c_int,
    pub beat: ::core::ffi::c_int,
    pub position: ::core::ffi::c_int,
    pub tempo: ::core::ffi::c_float,
    pub timesignatureupper: ::core::ffi::c_int,
    pub timesignaturelower: ::core::ffi::c_int,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES {
    pub eventid: FMOD_GUID,
    pub properties: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_ADVANCEDSETTINGS {
    pub cbsize: ::core::ffi::c_int,
    pub commandqueuesize: ::core::ffi::c_uint,
    pub handleinitialsize: ::core::ffi::c_uint,
    pub studioupdateperiod: ::core::ffi::c_int,
    pub idlesampledatapoolsize: ::core::ffi::c_int,
    pub streamingscheduledelay: ::core::ffi::c_uint,
    pub encryptionkey: *const ::core::ffi::c_char,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_CPU_USAGE {
    pub update: ::core::ffi::c_float,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_BUFFER_INFO {
    pub currentusage: ::core::ffi::c_int,
    pub peakusage: ::core::ffi::c_int,
    pub capacity: ::core::ffi::c_int,
    pub stallcount: ::core::ffi::c_int,
    pub stalltime: ::core::ffi::c_float,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_BUFFER_USAGE {
    pub studiocommandqueue: FMOD_STUDIO_BUFFER_INFO,
    pub studiohandle: FMOD_STUDIO_BUFFER_INFO,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_SOUND_INFO {
    pub name_or_data: *const ::core::ffi::c_char,
    pub mode: FMOD_MODE,
    pub exinfo: FMOD_CREATESOUNDEXINFO,
    pub subsoundindex: ::core::ffi::c_int,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_COMMAND_INFO {
    pub commandname: *const ::core::ffi::c_char,
    pub parentcommandindex: ::core::ffi::c_int,
    pub framenumber: ::core::ffi::c_int,
    pub frametime: ::core::ffi::c_float,
    pub instancetype: FMOD_STUDIO_INSTANCETYPE,
    pub outputtype: FMOD_STUDIO_INSTANCETYPE,
    pub instancehandle: ::core::ffi::c_uint,
    pub outputhandle: ::core::ffi::c_uint,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_STUDIO_MEMORY_USAGE {
    pub exclusive: ::core::ffi::c_int,
    pub inclusive: ::core::ffi::c_int,
    pub sampledata: ::core::ffi::c_int,
}

/*
    FMOD Studio callbacks.
*/
pub type FMOD_STUDIO_SYSTEM_CALLBACK                            = Option<unsafe extern "system" fn (system: *mut FMOD_STUDIO_SYSTEM, r#type: FMOD_STUDIO_SYSTEM_CALLBACK_TYPE, commanddata: *mut ::core::ffi::c_void, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_STUDIO_EVENT_CALLBACK                             = Option<unsafe extern "system" fn (r#type: FMOD_STUDIO_EVENT_CALLBACK_TYPE, event: *mut FMOD_STUDIO_EVENTINSTANCE, parameters: *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_STUDIO_COMMANDREPLAY_FRAME_CALLBACK               = Option<unsafe extern "system" fn (replay: *mut FMOD_STUDIO_COMMANDREPLAY, commandindex: ::core::ffi::c_int, currenttime: ::core::ffi::c_float, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_STUDIO_COMMANDREPLAY_LOAD_BANK_CALLBACK           = Option<unsafe extern "system" fn (replay: *mut FMOD_STUDIO_COMMANDREPLAY, commandindex: ::core::ffi::c_int, bankguid: *const FMOD_GUID, bankfilename: *const ::core::ffi::c_char, flags: FMOD_STUDIO_LOAD_BANK_FLAGS, bank: *mut *mut FMOD_STUDIO_BANK, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_STUDIO_COMMANDREPLAY_CREATE_INSTANCE_CALLBACK     = Option<unsafe extern "system" fn (replay: *mut FMOD_STUDIO_COMMANDREPLAY, commandindex: ::core::ffi::c_int, eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION, instance: *mut *mut FMOD_STUDIO_EVENTINSTANCE, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT>;
