/* automatically generated by rust-bindgen 0.59.2 */

/* Copyright (c), Firelight Technologies Pty, Ltd. 2004-2022. */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_SYSTEM {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_EVENTDESCRIPTION {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_EVENTINSTANCE {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BUS {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_VCA {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BANK {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_COMMANDREPLAY {
    _unused: [u8; 0],
}
pub type FMOD_STUDIO_INITFLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_PARAMETER_FLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_EVENT_CALLBACK_TYPE = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_LOAD_BANK_FLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_COMMANDCAPTURE_FLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_COMMANDREPLAY_FLAGS = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_LOADING_STATE_UNLOADING: FMOD_STUDIO_LOADING_STATE = 0;
pub const FMOD_STUDIO_LOADING_STATE_UNLOADED: FMOD_STUDIO_LOADING_STATE = 1;
pub const FMOD_STUDIO_LOADING_STATE_LOADING: FMOD_STUDIO_LOADING_STATE = 2;
pub const FMOD_STUDIO_LOADING_STATE_LOADED: FMOD_STUDIO_LOADING_STATE = 3;
pub const FMOD_STUDIO_LOADING_STATE_ERROR: FMOD_STUDIO_LOADING_STATE = 4;
pub const FMOD_STUDIO_LOADING_STATE_FORCEINT: FMOD_STUDIO_LOADING_STATE = 65536;
pub type FMOD_STUDIO_LOADING_STATE = ::std::os::raw::c_int;
pub const FMOD_STUDIO_LOAD_MEMORY: FMOD_STUDIO_LOAD_MEMORY_MODE = 0;
pub const FMOD_STUDIO_LOAD_MEMORY_POINT: FMOD_STUDIO_LOAD_MEMORY_MODE = 1;
pub const FMOD_STUDIO_LOAD_MEMORY_FORCEINT: FMOD_STUDIO_LOAD_MEMORY_MODE = 65536;
pub type FMOD_STUDIO_LOAD_MEMORY_MODE = ::std::os::raw::c_int;
pub const FMOD_STUDIO_PARAMETER_GAME_CONTROLLED: FMOD_STUDIO_PARAMETER_TYPE = 0;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE: FMOD_STUDIO_PARAMETER_TYPE = 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE: FMOD_STUDIO_PARAMETER_TYPE = 2;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION: FMOD_STUDIO_PARAMETER_TYPE = 3;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION: FMOD_STUDIO_PARAMETER_TYPE = 4;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION: FMOD_STUDIO_PARAMETER_TYPE = 5;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION: FMOD_STUDIO_PARAMETER_TYPE = 6;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED: FMOD_STUDIO_PARAMETER_TYPE = 7;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED_ABSOLUTE: FMOD_STUDIO_PARAMETER_TYPE = 8;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE_NORMALIZED: FMOD_STUDIO_PARAMETER_TYPE = 9;
pub const FMOD_STUDIO_PARAMETER_MAX: FMOD_STUDIO_PARAMETER_TYPE = 10;
pub const FMOD_STUDIO_PARAMETER_FORCEINT: FMOD_STUDIO_PARAMETER_TYPE = 65536;
pub type FMOD_STUDIO_PARAMETER_TYPE = ::std::os::raw::c_int;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_INTEGER: FMOD_STUDIO_USER_PROPERTY_TYPE = 0;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_BOOLEAN: FMOD_STUDIO_USER_PROPERTY_TYPE = 1;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_FLOAT: FMOD_STUDIO_USER_PROPERTY_TYPE = 2;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_STRING: FMOD_STUDIO_USER_PROPERTY_TYPE = 3;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_FORCEINT: FMOD_STUDIO_USER_PROPERTY_TYPE = 65536;
pub type FMOD_STUDIO_USER_PROPERTY_TYPE = ::std::os::raw::c_int;
pub const FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY: FMOD_STUDIO_EVENT_PROPERTY = 0;
pub const FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY: FMOD_STUDIO_EVENT_PROPERTY = 1;
pub const FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD: FMOD_STUDIO_EVENT_PROPERTY = 2;
pub const FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE: FMOD_STUDIO_EVENT_PROPERTY = 3;
pub const FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE: FMOD_STUDIO_EVENT_PROPERTY = 4;
pub const FMOD_STUDIO_EVENT_PROPERTY_COOLDOWN: FMOD_STUDIO_EVENT_PROPERTY = 5;
pub const FMOD_STUDIO_EVENT_PROPERTY_MAX: FMOD_STUDIO_EVENT_PROPERTY = 6;
pub const FMOD_STUDIO_EVENT_PROPERTY_FORCEINT: FMOD_STUDIO_EVENT_PROPERTY = 65536;
pub type FMOD_STUDIO_EVENT_PROPERTY = ::std::os::raw::c_int;
pub const FMOD_STUDIO_PLAYBACK_PLAYING: FMOD_STUDIO_PLAYBACK_STATE = 0;
pub const FMOD_STUDIO_PLAYBACK_SUSTAINING: FMOD_STUDIO_PLAYBACK_STATE = 1;
pub const FMOD_STUDIO_PLAYBACK_STOPPED: FMOD_STUDIO_PLAYBACK_STATE = 2;
pub const FMOD_STUDIO_PLAYBACK_STARTING: FMOD_STUDIO_PLAYBACK_STATE = 3;
pub const FMOD_STUDIO_PLAYBACK_STOPPING: FMOD_STUDIO_PLAYBACK_STATE = 4;
pub const FMOD_STUDIO_PLAYBACK_FORCEINT: FMOD_STUDIO_PLAYBACK_STATE = 65536;
pub type FMOD_STUDIO_PLAYBACK_STATE = ::std::os::raw::c_int;
pub const FMOD_STUDIO_STOP_ALLOWFADEOUT: FMOD_STUDIO_STOP_MODE = 0;
pub const FMOD_STUDIO_STOP_IMMEDIATE: FMOD_STUDIO_STOP_MODE = 1;
pub const FMOD_STUDIO_STOP_FORCEINT: FMOD_STUDIO_STOP_MODE = 65536;
pub type FMOD_STUDIO_STOP_MODE = ::std::os::raw::c_int;
pub const FMOD_STUDIO_INSTANCETYPE_NONE: FMOD_STUDIO_INSTANCETYPE = 0;
pub const FMOD_STUDIO_INSTANCETYPE_SYSTEM: FMOD_STUDIO_INSTANCETYPE = 1;
pub const FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION: FMOD_STUDIO_INSTANCETYPE = 2;
pub const FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE: FMOD_STUDIO_INSTANCETYPE = 3;
pub const FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE: FMOD_STUDIO_INSTANCETYPE = 4;
pub const FMOD_STUDIO_INSTANCETYPE_BUS: FMOD_STUDIO_INSTANCETYPE = 5;
pub const FMOD_STUDIO_INSTANCETYPE_VCA: FMOD_STUDIO_INSTANCETYPE = 6;
pub const FMOD_STUDIO_INSTANCETYPE_BANK: FMOD_STUDIO_INSTANCETYPE = 7;
pub const FMOD_STUDIO_INSTANCETYPE_COMMANDREPLAY: FMOD_STUDIO_INSTANCETYPE = 8;
pub const FMOD_STUDIO_INSTANCETYPE_FORCEINT: FMOD_STUDIO_INSTANCETYPE = 65536;
pub type FMOD_STUDIO_INSTANCETYPE = ::std::os::raw::c_int;
#[repr(C)]
// #[derive(Debug)] // rust-lang/rust#96513
#[derive(Copy, Clone)]
pub struct FMOD_STUDIO_BANK_INFO {
    pub size: ::std::os::raw::c_int,
    pub userdata: *mut ::std::os::raw::c_void,
    pub userdatalength: ::std::os::raw::c_int,
    pub opencallback: FMOD_FILE_OPEN_CALLBACK,
    pub closecallback: FMOD_FILE_CLOSE_CALLBACK,
    pub readcallback: FMOD_FILE_READ_CALLBACK,
    pub seekcallback: FMOD_FILE_SEEK_CALLBACK,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_BANK_INFO() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_BANK_INFO>(),
        56usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_BANK_INFO))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_BANK_INFO>(),
        8usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_BANK_INFO))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_BANK_INFO>())).size as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BANK_INFO),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_BANK_INFO>())).userdata as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BANK_INFO),
            "::",
            stringify!(userdata)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BANK_INFO>())).userdatalength as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BANK_INFO),
            "::",
            stringify!(userdatalength)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BANK_INFO>())).opencallback as *const _ as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BANK_INFO),
            "::",
            stringify!(opencallback)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BANK_INFO>())).closecallback as *const _ as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BANK_INFO),
            "::",
            stringify!(closecallback)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BANK_INFO>())).readcallback as *const _ as usize
        },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BANK_INFO),
            "::",
            stringify!(readcallback)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BANK_INFO>())).seekcallback as *const _ as usize
        },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BANK_INFO),
            "::",
            stringify!(seekcallback)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_PARAMETER_ID {
    pub data1: ::std::os::raw::c_uint,
    pub data2: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_PARAMETER_ID() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_PARAMETER_ID>(),
        8usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_PARAMETER_ID))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_PARAMETER_ID>(),
        4usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_PARAMETER_ID))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_ID>())).data1 as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_ID),
            "::",
            stringify!(data1)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_ID>())).data2 as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_ID),
            "::",
            stringify!(data2)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_PARAMETER_DESCRIPTION {
    pub name: *const ::std::os::raw::c_char,
    pub id: FMOD_STUDIO_PARAMETER_ID,
    pub minimum: f32,
    pub maximum: f32,
    pub defaultvalue: f32,
    pub type_: FMOD_STUDIO_PARAMETER_TYPE,
    pub flags: FMOD_STUDIO_PARAMETER_FLAGS,
    pub guid: FMOD_GUID,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_PARAMETER_DESCRIPTION() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_PARAMETER_DESCRIPTION>(),
        56usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_PARAMETER_DESCRIPTION>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).name as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).id as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).minimum as *const _
                as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(minimum)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).maximum as *const _
                as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(maximum)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).defaultvalue as *const _
                as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(defaultvalue)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).type_ as *const _ as usize
        },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).flags as *const _ as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(flags)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PARAMETER_DESCRIPTION>())).guid as *const _ as usize
        },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PARAMETER_DESCRIPTION),
            "::",
            stringify!(guid)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FMOD_STUDIO_USER_PROPERTY {
    pub name: *const ::std::os::raw::c_char,
    pub type_: FMOD_STUDIO_USER_PROPERTY_TYPE,
    pub __bindgen_anon_1: FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1 {
    pub intvalue: ::std::os::raw::c_int,
    pub boolvalue: FMOD_BOOL,
    pub floatvalue: f32,
    pub stringvalue: *const ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>(),
        8usize,
        concat!(
            "Size of: ",
            stringify!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>())).intvalue as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1),
            "::",
            stringify!(intvalue)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>())).boolvalue
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1),
            "::",
            stringify!(boolvalue)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>())).floatvalue
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1),
            "::",
            stringify!(floatvalue)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>())).stringvalue
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1),
            "::",
            stringify!(stringvalue)
        )
    );
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_USER_PROPERTY() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_USER_PROPERTY>(),
        24usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_USER_PROPERTY))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_USER_PROPERTY>(),
        8usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_USER_PROPERTY))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_USER_PROPERTY>())).name as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_USER_PROPERTY),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_USER_PROPERTY>())).type_ as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_USER_PROPERTY),
            "::",
            stringify!(type_)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES {
    pub name: *const ::std::os::raw::c_char,
    pub sound: *mut FMOD_SOUND,
    pub subsoundIndex: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES>(),
        24usize,
        concat!(
            "Size of: ",
            stringify!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES>())).name as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES>())).sound as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES),
            "::",
            stringify!(sound)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES>())).subsoundIndex
                as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES),
            "::",
            stringify!(subsoundIndex)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES {
    pub name: *const ::std::os::raw::c_char,
    pub dsp: *mut FMOD_DSP,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES>())).name as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES>())).dsp as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES),
            "::",
            stringify!(dsp)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES {
    pub name: *const ::std::os::raw::c_char,
    pub position: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES>())).name as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES>())).position as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES),
            "::",
            stringify!(position)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES {
    pub bar: ::std::os::raw::c_int,
    pub beat: ::std::os::raw::c_int,
    pub position: ::std::os::raw::c_int,
    pub tempo: f32,
    pub timesignatureupper: ::std::os::raw::c_int,
    pub timesignaturelower: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>(),
        24usize,
        concat!(
            "Size of: ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>())).bar as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES),
            "::",
            stringify!(bar)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>())).beat as *const _
                as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES),
            "::",
            stringify!(beat)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>())).position as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES),
            "::",
            stringify!(position)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>())).tempo as *const _
                as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES),
            "::",
            stringify!(tempo)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>())).timesignatureupper
                as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES),
            "::",
            stringify!(timesignatureupper)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>())).timesignaturelower
                as *const _ as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES),
            "::",
            stringify!(timesignaturelower)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES {
    pub eventid: FMOD_GUID,
    pub properties: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES>(),
        40usize,
        concat!(
            "Size of: ",
            stringify!(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES>())).eventid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES),
            "::",
            stringify!(eventid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES>())).properties
                as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES),
            "::",
            stringify!(properties)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_ADVANCEDSETTINGS {
    pub cbsize: ::std::os::raw::c_int,
    pub commandqueuesize: ::std::os::raw::c_uint,
    pub handleinitialsize: ::std::os::raw::c_uint,
    pub studioupdateperiod: ::std::os::raw::c_int,
    pub idlesampledatapoolsize: ::std::os::raw::c_int,
    pub streamingscheduledelay: ::std::os::raw::c_uint,
    pub encryptionkey: *const ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_ADVANCEDSETTINGS() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_ADVANCEDSETTINGS>(),
        32usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_ADVANCEDSETTINGS))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_ADVANCEDSETTINGS>(),
        8usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_ADVANCEDSETTINGS))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_ADVANCEDSETTINGS>())).cbsize as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_ADVANCEDSETTINGS),
            "::",
            stringify!(cbsize)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_ADVANCEDSETTINGS>())).commandqueuesize as *const _
                as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_ADVANCEDSETTINGS),
            "::",
            stringify!(commandqueuesize)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_ADVANCEDSETTINGS>())).handleinitialsize as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_ADVANCEDSETTINGS),
            "::",
            stringify!(handleinitialsize)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_ADVANCEDSETTINGS>())).studioupdateperiod as *const _
                as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_ADVANCEDSETTINGS),
            "::",
            stringify!(studioupdateperiod)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_ADVANCEDSETTINGS>())).idlesampledatapoolsize
                as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_ADVANCEDSETTINGS),
            "::",
            stringify!(idlesampledatapoolsize)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_ADVANCEDSETTINGS>())).streamingscheduledelay
                as *const _ as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_ADVANCEDSETTINGS),
            "::",
            stringify!(streamingscheduledelay)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_ADVANCEDSETTINGS>())).encryptionkey as *const _
                as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_ADVANCEDSETTINGS),
            "::",
            stringify!(encryptionkey)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_CPU_USAGE {
    pub update: f32,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_CPU_USAGE() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_CPU_USAGE>(),
        4usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_CPU_USAGE))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_CPU_USAGE>(),
        4usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_CPU_USAGE))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_CPU_USAGE>())).update as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_CPU_USAGE),
            "::",
            stringify!(update)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BUFFER_INFO {
    pub currentusage: ::std::os::raw::c_int,
    pub peakusage: ::std::os::raw::c_int,
    pub capacity: ::std::os::raw::c_int,
    pub stallcount: ::std::os::raw::c_int,
    pub stalltime: f32,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_BUFFER_INFO() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_BUFFER_INFO>(),
        20usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_BUFFER_INFO))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_BUFFER_INFO>(),
        4usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_BUFFER_INFO))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BUFFER_INFO>())).currentusage as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BUFFER_INFO),
            "::",
            stringify!(currentusage)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BUFFER_INFO>())).peakusage as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BUFFER_INFO),
            "::",
            stringify!(peakusage)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BUFFER_INFO>())).capacity as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BUFFER_INFO),
            "::",
            stringify!(capacity)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BUFFER_INFO>())).stallcount as *const _ as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BUFFER_INFO),
            "::",
            stringify!(stallcount)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BUFFER_INFO>())).stalltime as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BUFFER_INFO),
            "::",
            stringify!(stalltime)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BUFFER_USAGE {
    pub studiocommandqueue: FMOD_STUDIO_BUFFER_INFO,
    pub studiohandle: FMOD_STUDIO_BUFFER_INFO,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_BUFFER_USAGE() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_BUFFER_USAGE>(),
        40usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_BUFFER_USAGE))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_BUFFER_USAGE>(),
        4usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_BUFFER_USAGE))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BUFFER_USAGE>())).studiocommandqueue as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BUFFER_USAGE),
            "::",
            stringify!(studiocommandqueue)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_BUFFER_USAGE>())).studiohandle as *const _ as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_BUFFER_USAGE),
            "::",
            stringify!(studiohandle)
        )
    );
}
#[repr(C)]
// #[derive(Debug)] // rust-lang/rust#96513
#[derive(Copy, Clone)]
pub struct FMOD_STUDIO_SOUND_INFO {
    pub name_or_data: *const ::std::os::raw::c_char,
    pub mode: FMOD_MODE,
    pub exinfo: FMOD_CREATESOUNDEXINFO,
    pub subsoundindex: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_SOUND_INFO() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_SOUND_INFO>(),
        248usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_SOUND_INFO))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_SOUND_INFO>(),
        8usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_SOUND_INFO))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_SOUND_INFO>())).name_or_data as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_SOUND_INFO),
            "::",
            stringify!(name_or_data)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_SOUND_INFO>())).mode as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_SOUND_INFO),
            "::",
            stringify!(mode)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<FMOD_STUDIO_SOUND_INFO>())).exinfo as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_SOUND_INFO),
            "::",
            stringify!(exinfo)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_SOUND_INFO>())).subsoundindex as *const _ as usize
        },
        240usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_SOUND_INFO),
            "::",
            stringify!(subsoundindex)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_COMMAND_INFO {
    pub commandname: *const ::std::os::raw::c_char,
    pub parentcommandindex: ::std::os::raw::c_int,
    pub framenumber: ::std::os::raw::c_int,
    pub frametime: f32,
    pub instancetype: FMOD_STUDIO_INSTANCETYPE,
    pub outputtype: FMOD_STUDIO_INSTANCETYPE,
    pub instancehandle: ::std::os::raw::c_uint,
    pub outputhandle: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_COMMAND_INFO() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_COMMAND_INFO>(),
        40usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_COMMAND_INFO))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_COMMAND_INFO>(),
        8usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_COMMAND_INFO))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).commandname as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(commandname)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).parentcommandindex as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(parentcommandindex)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).framenumber as *const _ as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(framenumber)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).frametime as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(frametime)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).instancetype as *const _ as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(instancetype)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).outputtype as *const _ as usize
        },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(outputtype)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).instancehandle as *const _ as usize
        },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(instancehandle)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_COMMAND_INFO>())).outputhandle as *const _ as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_COMMAND_INFO),
            "::",
            stringify!(outputhandle)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_MEMORY_USAGE {
    pub exclusive: ::std::os::raw::c_int,
    pub inclusive: ::std::os::raw::c_int,
    pub sampledata: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_FMOD_STUDIO_MEMORY_USAGE() {
    assert_eq!(
        ::std::mem::size_of::<FMOD_STUDIO_MEMORY_USAGE>(),
        12usize,
        concat!("Size of: ", stringify!(FMOD_STUDIO_MEMORY_USAGE))
    );
    assert_eq!(
        ::std::mem::align_of::<FMOD_STUDIO_MEMORY_USAGE>(),
        4usize,
        concat!("Alignment of ", stringify!(FMOD_STUDIO_MEMORY_USAGE))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_MEMORY_USAGE>())).exclusive as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_MEMORY_USAGE),
            "::",
            stringify!(exclusive)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_MEMORY_USAGE>())).inclusive as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_MEMORY_USAGE),
            "::",
            stringify!(inclusive)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<FMOD_STUDIO_MEMORY_USAGE>())).sampledata as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(FMOD_STUDIO_MEMORY_USAGE),
            "::",
            stringify!(sampledata)
        )
    );
}
pub type FMOD_STUDIO_SYSTEM_CALLBACK = ::std::option::Option<
    unsafe extern "system" fn(
        system: *mut FMOD_STUDIO_SYSTEM,
        type_: FMOD_STUDIO_SYSTEM_CALLBACK_TYPE,
        commanddata: *mut ::std::os::raw::c_void,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_EVENT_CALLBACK = ::std::option::Option<
    unsafe extern "system" fn(
        type_: FMOD_STUDIO_EVENT_CALLBACK_TYPE,
        event: *mut FMOD_STUDIO_EVENTINSTANCE,
        parameters: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_COMMANDREPLAY_FRAME_CALLBACK = ::std::option::Option<
    unsafe extern "system" fn(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        currenttime: f32,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_COMMANDREPLAY_LOAD_BANK_CALLBACK = ::std::option::Option<
    unsafe extern "system" fn(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        bankguid: *const FMOD_GUID,
        bankfilename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_COMMANDREPLAY_CREATE_INSTANCE_CALLBACK = ::std::option::Option<
    unsafe extern "system" fn(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        instance: *mut *mut FMOD_STUDIO_EVENTINSTANCE,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
extern "system" {
    pub fn FMOD_Studio_ParseID(
        idstring: *const ::std::os::raw::c_char,
        id: *mut FMOD_GUID,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_Create(
        system: *mut *mut FMOD_STUDIO_SYSTEM,
        headerversion: ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_IsValid(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_BOOL;
}
extern "system" {
    pub fn FMOD_Studio_System_SetAdvancedSettings(
        system: *mut FMOD_STUDIO_SYSTEM,
        settings: *mut FMOD_STUDIO_ADVANCEDSETTINGS,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetAdvancedSettings(
        system: *mut FMOD_STUDIO_SYSTEM,
        settings: *mut FMOD_STUDIO_ADVANCEDSETTINGS,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_Initialize(
        system: *mut FMOD_STUDIO_SYSTEM,
        maxchannels: ::std::os::raw::c_int,
        studioflags: FMOD_STUDIO_INITFLAGS,
        flags: FMOD_INITFLAGS,
        extradriverdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_Release(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_Update(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetCoreSystem(
        system: *mut FMOD_STUDIO_SYSTEM,
        coresystem: *mut *mut FMOD_SYSTEM,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetEvent(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        event: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetBus(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        bus: *mut *mut FMOD_STUDIO_BUS,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetVCA(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        vca: *mut *mut FMOD_STUDIO_VCA,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetBank(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetEventByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        event: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetBusByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        bus: *mut *mut FMOD_STUDIO_BUS,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetVCAByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        vca: *mut *mut FMOD_STUDIO_VCA,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetBankByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetSoundInfo(
        system: *mut FMOD_STUDIO_SYSTEM,
        key: *const ::std::os::raw::c_char,
        info: *mut FMOD_STUDIO_SOUND_INFO,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterDescriptionByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterDescriptionByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterLabelByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterLabelByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetParameterByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetParameterByIDWithLabel(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetParametersByIDs(
        system: *mut FMOD_STUDIO_SYSTEM,
        ids: *const FMOD_STUDIO_PARAMETER_ID,
        values: *mut f32,
        count: ::std::os::raw::c_int,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetParameterByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetParameterByNameWithLabel(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_LookupID(
        system: *mut FMOD_STUDIO_SYSTEM,
        path: *const ::std::os::raw::c_char,
        id: *mut FMOD_GUID,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_LookupPath(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetNumListeners(
        system: *mut FMOD_STUDIO_SYSTEM,
        numlisteners: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetNumListeners(
        system: *mut FMOD_STUDIO_SYSTEM,
        numlisteners: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetListenerAttributes(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        attributes: *mut FMOD_3D_ATTRIBUTES,
        attenuationposition: *mut FMOD_VECTOR,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetListenerAttributes(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        attributes: *const FMOD_3D_ATTRIBUTES,
        attenuationposition: *const FMOD_VECTOR,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetListenerWeight(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        weight: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetListenerWeight(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        weight: f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_LoadBankFile(
        system: *mut FMOD_STUDIO_SYSTEM,
        filename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_LoadBankMemory(
        system: *mut FMOD_STUDIO_SYSTEM,
        buffer: *const ::std::os::raw::c_char,
        length: ::std::os::raw::c_int,
        mode: FMOD_STUDIO_LOAD_MEMORY_MODE,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_LoadBankCustom(
        system: *mut FMOD_STUDIO_SYSTEM,
        info: *const FMOD_STUDIO_BANK_INFO,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_RegisterPlugin(
        system: *mut FMOD_STUDIO_SYSTEM,
        description: *const FMOD_DSP_DESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_UnregisterPlugin(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_UnloadAll(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_FlushCommands(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_FlushSampleLoading(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_StartCommandCapture(
        system: *mut FMOD_STUDIO_SYSTEM,
        filename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_COMMANDCAPTURE_FLAGS,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_StopCommandCapture(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_LoadCommandReplay(
        system: *mut FMOD_STUDIO_SYSTEM,
        filename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_COMMANDREPLAY_FLAGS,
        replay: *mut *mut FMOD_STUDIO_COMMANDREPLAY,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetBankCount(
        system: *mut FMOD_STUDIO_SYSTEM,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetBankList(
        system: *mut FMOD_STUDIO_SYSTEM,
        array: *mut *mut FMOD_STUDIO_BANK,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterDescriptionCount(
        system: *mut FMOD_STUDIO_SYSTEM,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetParameterDescriptionList(
        system: *mut FMOD_STUDIO_SYSTEM,
        array: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetCPUUsage(
        system: *mut FMOD_STUDIO_SYSTEM,
        usage: *mut FMOD_STUDIO_CPU_USAGE,
        usage_core: *mut FMOD_CPU_USAGE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetBufferUsage(
        system: *mut FMOD_STUDIO_SYSTEM,
        usage: *mut FMOD_STUDIO_BUFFER_USAGE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_ResetBufferUsage(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetCallback(
        system: *mut FMOD_STUDIO_SYSTEM,
        callback: FMOD_STUDIO_SYSTEM_CALLBACK,
        callbackmask: FMOD_STUDIO_SYSTEM_CALLBACK_TYPE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_SetUserData(
        system: *mut FMOD_STUDIO_SYSTEM,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetUserData(
        system: *mut FMOD_STUDIO_SYSTEM,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_System_GetMemoryUsage(
        system: *mut FMOD_STUDIO_SYSTEM,
        memoryusage: *mut FMOD_STUDIO_MEMORY_USAGE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_IsValid(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_BOOL;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetID(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        id: *mut FMOD_GUID,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetPath(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionCount(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionByIndex(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        index: ::std::os::raw::c_int,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionByName(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        name: *const ::std::os::raw::c_char,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionByID(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        id: FMOD_STUDIO_PARAMETER_ID,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetParameterLabelByIndex(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        index: ::std::os::raw::c_int,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetParameterLabelByName(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        name: *const ::std::os::raw::c_char,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetParameterLabelByID(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        id: FMOD_STUDIO_PARAMETER_ID,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetUserPropertyCount(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetUserPropertyByIndex(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        index: ::std::os::raw::c_int,
        property: *mut FMOD_STUDIO_USER_PROPERTY,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetUserProperty(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        name: *const ::std::os::raw::c_char,
        property: *mut FMOD_STUDIO_USER_PROPERTY,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetLength(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        length: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetMinMaxDistance(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        min: *mut f32,
        max: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetSoundSize(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        size: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_IsSnapshot(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        snapshot: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_IsOneshot(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        oneshot: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_IsStream(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        isStream: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_Is3D(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        is3D: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_IsDopplerEnabled(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        doppler: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_HasSustainPoint(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        sustainPoint: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_CreateInstance(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        instance: *mut *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetInstanceCount(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetInstanceList(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        array: *mut *mut FMOD_STUDIO_EVENTINSTANCE,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_LoadSampleData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_UnloadSampleData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetSampleLoadingState(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        state: *mut FMOD_STUDIO_LOADING_STATE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_ReleaseAllInstances(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_SetCallback(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        callback: FMOD_STUDIO_EVENT_CALLBACK,
        callbackmask: FMOD_STUDIO_EVENT_CALLBACK_TYPE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_GetUserData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventDescription_SetUserData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_IsValid(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_BOOL;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetDescription(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        description: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetVolume(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        volume: *mut f32,
        finalvolume: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetVolume(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        volume: f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetPitch(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        pitch: *mut f32,
        finalpitch: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetPitch(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        pitch: f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_Get3DAttributes(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        attributes: *mut FMOD_3D_ATTRIBUTES,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_Set3DAttributes(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        attributes: *mut FMOD_3D_ATTRIBUTES,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetListenerMask(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        mask: *mut ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetListenerMask(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        mask: ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetProperty(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: FMOD_STUDIO_EVENT_PROPERTY,
        value: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetProperty(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: FMOD_STUDIO_EVENT_PROPERTY,
        value: f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetReverbLevel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: ::std::os::raw::c_int,
        level: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetReverbLevel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: ::std::os::raw::c_int,
        level: f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetPaused(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        paused: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetPaused(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        paused: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_Start(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_Stop(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        mode: FMOD_STUDIO_STOP_MODE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetTimelinePosition(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        position: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetTimelinePosition(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        position: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetPlaybackState(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        state: *mut FMOD_STUDIO_PLAYBACK_STATE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetChannelGroup(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        group: *mut *mut FMOD_CHANNELGROUP,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetMinMaxDistance(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        min: *mut f32,
        max: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_Release(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_IsVirtual(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        virtualstate: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetParameterByName(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        name: *const ::std::os::raw::c_char,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetParameterByName(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        name: *const ::std::os::raw::c_char,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetParameterByNameWithLabel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        name: *const ::std::os::raw::c_char,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetParameterByID(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetParameterByID(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetParameterByIDWithLabel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        id: FMOD_STUDIO_PARAMETER_ID,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetParametersByIDs(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        ids: *const FMOD_STUDIO_PARAMETER_ID,
        values: *mut f32,
        count: ::std::os::raw::c_int,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_KeyOff(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetCallback(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        callback: FMOD_STUDIO_EVENT_CALLBACK,
        callbackmask: FMOD_STUDIO_EVENT_CALLBACK_TYPE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetUserData(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_SetUserData(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetCPUUsage(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        exclusive: *mut ::std::os::raw::c_uint,
        inclusive: *mut ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_EventInstance_GetMemoryUsage(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        memoryusage: *mut FMOD_STUDIO_MEMORY_USAGE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_IsValid(bus: *mut FMOD_STUDIO_BUS) -> FMOD_BOOL;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetID(bus: *mut FMOD_STUDIO_BUS, id: *mut FMOD_GUID) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetPath(
        bus: *mut FMOD_STUDIO_BUS,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetVolume(
        bus: *mut FMOD_STUDIO_BUS,
        volume: *mut f32,
        finalvolume: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_SetVolume(bus: *mut FMOD_STUDIO_BUS, volume: f32) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetPaused(
        bus: *mut FMOD_STUDIO_BUS,
        paused: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_SetPaused(bus: *mut FMOD_STUDIO_BUS, paused: FMOD_BOOL) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetMute(bus: *mut FMOD_STUDIO_BUS, mute: *mut FMOD_BOOL) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_SetMute(bus: *mut FMOD_STUDIO_BUS, mute: FMOD_BOOL) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_StopAllEvents(
        bus: *mut FMOD_STUDIO_BUS,
        mode: FMOD_STUDIO_STOP_MODE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetPortIndex(
        bus: *mut FMOD_STUDIO_BUS,
        index: *mut FMOD_PORT_INDEX,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_SetPortIndex(
        bus: *mut FMOD_STUDIO_BUS,
        index: FMOD_PORT_INDEX,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_LockChannelGroup(bus: *mut FMOD_STUDIO_BUS) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_UnlockChannelGroup(bus: *mut FMOD_STUDIO_BUS) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetChannelGroup(
        bus: *mut FMOD_STUDIO_BUS,
        group: *mut *mut FMOD_CHANNELGROUP,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetCPUUsage(
        bus: *mut FMOD_STUDIO_BUS,
        exclusive: *mut ::std::os::raw::c_uint,
        inclusive: *mut ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bus_GetMemoryUsage(
        bus: *mut FMOD_STUDIO_BUS,
        memoryusage: *mut FMOD_STUDIO_MEMORY_USAGE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_VCA_IsValid(vca: *mut FMOD_STUDIO_VCA) -> FMOD_BOOL;
}
extern "system" {
    pub fn FMOD_Studio_VCA_GetID(vca: *mut FMOD_STUDIO_VCA, id: *mut FMOD_GUID) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_VCA_GetPath(
        vca: *mut FMOD_STUDIO_VCA,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_VCA_GetVolume(
        vca: *mut FMOD_STUDIO_VCA,
        volume: *mut f32,
        finalvolume: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_VCA_SetVolume(vca: *mut FMOD_STUDIO_VCA, volume: f32) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_IsValid(bank: *mut FMOD_STUDIO_BANK) -> FMOD_BOOL;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetID(bank: *mut FMOD_STUDIO_BANK, id: *mut FMOD_GUID) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetPath(
        bank: *mut FMOD_STUDIO_BANK,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_Unload(bank: *mut FMOD_STUDIO_BANK) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_LoadSampleData(bank: *mut FMOD_STUDIO_BANK) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_UnloadSampleData(bank: *mut FMOD_STUDIO_BANK) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetLoadingState(
        bank: *mut FMOD_STUDIO_BANK,
        state: *mut FMOD_STUDIO_LOADING_STATE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetSampleLoadingState(
        bank: *mut FMOD_STUDIO_BANK,
        state: *mut FMOD_STUDIO_LOADING_STATE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetStringCount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetStringInfo(
        bank: *mut FMOD_STUDIO_BANK,
        index: ::std::os::raw::c_int,
        id: *mut FMOD_GUID,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetEventCount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetEventList(
        bank: *mut FMOD_STUDIO_BANK,
        array: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetBusCount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetBusList(
        bank: *mut FMOD_STUDIO_BANK,
        array: *mut *mut FMOD_STUDIO_BUS,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetVCACount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetVCAList(
        bank: *mut FMOD_STUDIO_BANK,
        array: *mut *mut FMOD_STUDIO_VCA,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_GetUserData(
        bank: *mut FMOD_STUDIO_BANK,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_Bank_SetUserData(
        bank: *mut FMOD_STUDIO_BANK,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_IsValid(replay: *mut FMOD_STUDIO_COMMANDREPLAY) -> FMOD_BOOL;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetSystem(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        system: *mut *mut FMOD_STUDIO_SYSTEM,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetLength(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        length: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetCommandCount(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetCommandInfo(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        info: *mut FMOD_STUDIO_COMMAND_INFO,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetCommandString(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        buffer: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetCommandAtTime(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        time: f32,
        commandindex: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SetBankPath(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        bankPath: *const ::std::os::raw::c_char,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_Start(replay: *mut FMOD_STUDIO_COMMANDREPLAY) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_Stop(replay: *mut FMOD_STUDIO_COMMANDREPLAY) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SeekToTime(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        time: f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SeekToCommand(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetPaused(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        paused: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SetPaused(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        paused: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetPlaybackState(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        state: *mut FMOD_STUDIO_PLAYBACK_STATE,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetCurrentCommand(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: *mut ::std::os::raw::c_int,
        currenttime: *mut f32,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_Release(replay: *mut FMOD_STUDIO_COMMANDREPLAY)
        -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SetFrameCallback(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        callback: FMOD_STUDIO_COMMANDREPLAY_FRAME_CALLBACK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SetLoadBankCallback(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        callback: FMOD_STUDIO_COMMANDREPLAY_LOAD_BANK_CALLBACK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SetCreateInstanceCallback(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        callback: FMOD_STUDIO_COMMANDREPLAY_CREATE_INSTANCE_CALLBACK,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_GetUserData(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
extern "system" {
    pub fn FMOD_Studio_CommandReplay_SetUserData(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
