// @generated by carcinize.nu from FMOD headers
/* ======================================================================================== */
/* FMOD Core API - DSP header file.                                                         */
/* Copyright (c), Firelight Technologies Pty, Ltd. 2004-2025.                               */
/*                                                                                          */
/* Use this header if you are wanting to develop your own DSP plugin to use with FMODs      */
/* dsp system.  With this header you can make your own DSP plugin that FMOD can             */
/* register and use.  See the documentation and examples on how to make a working plugin.   */
/*                                                                                          */
/* For more detail visit:                                                                   */
/* https://fmod.com/docs/2.03/api/plugin-api-dsp.html                                       */
/* =========================================================================================*/


/*
    DSP Constants
*/
pub const FMOD_PLUGIN_SDK_VERSION:             ::core::ffi::c_int = 110;
pub const FMOD_DSP_GETPARAM_VALUESTR_LENGTH:   ::core::ffi::c_int = 32;

pub const FMOD_DSP_PROCESS_PERFORM: FMOD_DSP_PROCESS_OPERATION = 0;
pub const FMOD_DSP_PROCESS_QUERY: FMOD_DSP_PROCESS_OPERATION = FMOD_DSP_PROCESS_PERFORM + 1;
pub type FMOD_DSP_PROCESS_OPERATION = ::core::ffi::c_int;

pub const FMOD_DSP_PAN_SURROUND_DEFAULT: FMOD_DSP_PAN_SURROUND_FLAGS = 0;
pub const FMOD_DSP_PAN_SURROUND_ROTATION_NOT_BIASED: FMOD_DSP_PAN_SURROUND_FLAGS = 1;
pub type FMOD_DSP_PAN_SURROUND_FLAGS = ::core::ffi::c_int;

pub const FMOD_DSP_PARAMETER_TYPE_FLOAT: FMOD_DSP_PARAMETER_TYPE = 0;
pub const FMOD_DSP_PARAMETER_TYPE_INT: FMOD_DSP_PARAMETER_TYPE = FMOD_DSP_PARAMETER_TYPE_FLOAT + 1;
pub const FMOD_DSP_PARAMETER_TYPE_BOOL: FMOD_DSP_PARAMETER_TYPE = FMOD_DSP_PARAMETER_TYPE_INT + 1;
pub const FMOD_DSP_PARAMETER_TYPE_DATA: FMOD_DSP_PARAMETER_TYPE = FMOD_DSP_PARAMETER_TYPE_BOOL + 1;

pub const FMOD_DSP_PARAMETER_TYPE_MAX: FMOD_DSP_PARAMETER_TYPE = FMOD_DSP_PARAMETER_TYPE_DATA + 1;
pub type FMOD_DSP_PARAMETER_TYPE = ::core::ffi::c_int;

pub const FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_LINEAR: FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE = 0;
pub const FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_AUTO: FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE = FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_LINEAR + 1;
pub const FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_PIECEWISE_LINEAR: FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE = FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_AUTO + 1;
pub type FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE = ::core::ffi::c_int;

pub const FMOD_DSP_PARAMETER_DATA_TYPE_USER: FMOD_DSP_PARAMETER_DATA_TYPE = 0;
pub const FMOD_DSP_PARAMETER_DATA_TYPE_OVERALLGAIN: FMOD_DSP_PARAMETER_DATA_TYPE = -1;
pub const FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES: FMOD_DSP_PARAMETER_DATA_TYPE = -2;
pub const FMOD_DSP_PARAMETER_DATA_TYPE_SIDECHAIN: FMOD_DSP_PARAMETER_DATA_TYPE = -3;
pub const FMOD_DSP_PARAMETER_DATA_TYPE_FFT: FMOD_DSP_PARAMETER_DATA_TYPE = -4;
pub const FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI: FMOD_DSP_PARAMETER_DATA_TYPE = -5;
pub const FMOD_DSP_PARAMETER_DATA_TYPE_ATTENUATION_RANGE: FMOD_DSP_PARAMETER_DATA_TYPE = -6;
pub const FMOD_DSP_PARAMETER_DATA_TYPE_DYNAMIC_RESPONSE: FMOD_DSP_PARAMETER_DATA_TYPE = -7;
pub type FMOD_DSP_PARAMETER_DATA_TYPE = ::core::ffi::c_int;

/*
    DSP Callbacks
*/
pub type FMOD_DSP_CREATE_CALLBACK                     = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE) -> FMOD_RESULT>;
pub type FMOD_DSP_RELEASE_CALLBACK                    = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE) -> FMOD_RESULT>;
pub type FMOD_DSP_RESET_CALLBACK                      = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE) -> FMOD_RESULT>;
pub type FMOD_DSP_READ_CALLBACK                       = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, inbuffer: *mut ::core::ffi::c_float, outbuffer: *mut ::core::ffi::c_float, length: ::core::ffi::c_uint, inchannels: ::core::ffi::c_int, outchannels: *mut ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_DSP_PROCESS_CALLBACK                    = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, length: ::core::ffi::c_uint, inbufferarray: *const FMOD_DSP_BUFFER_ARRAY, outbufferarray: *mut FMOD_DSP_BUFFER_ARRAY, inputsidle: FMOD_BOOL, op: FMOD_DSP_PROCESS_OPERATION) -> FMOD_RESULT>;
pub type FMOD_DSP_SETPOSITION_CALLBACK                = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, pos: ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_DSP_SHOULDIPROCESS_CALLBACK             = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, inputsidle: FMOD_BOOL, length: ::core::ffi::c_uint, inmask: FMOD_CHANNELMASK, inchannels: ::core::ffi::c_int, speakermode: FMOD_SPEAKERMODE) -> FMOD_RESULT>;
pub type FMOD_DSP_SETPARAM_FLOAT_CALLBACK             = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, value: ::core::ffi::c_float) -> FMOD_RESULT>;
pub type FMOD_DSP_SETPARAM_INT_CALLBACK               = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, value: ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_DSP_SETPARAM_BOOL_CALLBACK              = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, value: FMOD_BOOL) -> FMOD_RESULT>;
pub type FMOD_DSP_SETPARAM_DATA_CALLBACK              = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, data: *mut ::core::ffi::c_void, length: ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_DSP_GETPARAM_FLOAT_CALLBACK             = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, value: *mut ::core::ffi::c_float, valuestr: *mut ::core::ffi::c_char) -> FMOD_RESULT>;
pub type FMOD_DSP_GETPARAM_INT_CALLBACK               = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, value: *mut ::core::ffi::c_int, valuestr: *mut ::core::ffi::c_char) -> FMOD_RESULT>;
pub type FMOD_DSP_GETPARAM_BOOL_CALLBACK              = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, value: *mut FMOD_BOOL, valuestr: *mut ::core::ffi::c_char) -> FMOD_RESULT>;
pub type FMOD_DSP_GETPARAM_DATA_CALLBACK              = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, index: ::core::ffi::c_int, data: *mut *mut ::core::ffi::c_void, length: *mut ::core::ffi::c_uint, valuestr: *mut ::core::ffi::c_char) -> FMOD_RESULT>;
pub type FMOD_DSP_SYSTEM_REGISTER_CALLBACK            = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE) -> FMOD_RESULT>;
pub type FMOD_DSP_SYSTEM_DEREGISTER_CALLBACK          = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE) -> FMOD_RESULT>;
pub type FMOD_DSP_SYSTEM_MIX_CALLBACK                 = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, stage: ::core::ffi::c_int) -> FMOD_RESULT>;

/*
    DSP Functions
*/
pub type FMOD_DSP_ALLOC_FUNC                          = Option<unsafe extern "system" fn (size: ::core::ffi::c_uint, r#type: FMOD_MEMORY_TYPE, sourcestr: *const ::core::ffi::c_char) -> *mut ::core::ffi::c_void      >;
pub type FMOD_DSP_REALLOC_FUNC                        = Option<unsafe extern "system" fn (ptr: *mut ::core::ffi::c_void, size: ::core::ffi::c_uint, r#type: FMOD_MEMORY_TYPE, sourcestr: *const ::core::ffi::c_char) -> *mut ::core::ffi::c_void      >;
pub type FMOD_DSP_FREE_FUNC                           = Option<unsafe extern "system" fn (ptr: *mut ::core::ffi::c_void, r#type: FMOD_MEMORY_TYPE, sourcestr: *const ::core::ffi::c_char)>;
pub type FMOD_DSP_LOG_FUNC                            = unsafe extern "C" fn (level: FMOD_DEBUG_FLAGS, file: *const ::core::ffi::c_char, line: ::core::ffi::c_int, function: *const ::core::ffi::c_char, str: *const ::core::ffi::c_char, ...);
pub type FMOD_DSP_GETSAMPLERATE_FUNC                  = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, rate: *mut ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_DSP_GETBLOCKSIZE_FUNC                   = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, blocksize: *mut ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_DSP_GETSPEAKERMODE_FUNC                 = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, speakermode_mixer: *mut FMOD_SPEAKERMODE, speakermode_output: *mut FMOD_SPEAKERMODE) -> FMOD_RESULT>;
pub type FMOD_DSP_GETCLOCK_FUNC                       = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, clock: *mut ::core::ffi::c_ulonglong, offset: *mut ::core::ffi::c_uint, length: *mut ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_DSP_GETLISTENERATTRIBUTES_FUNC          = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, numlisteners: *mut ::core::ffi::c_int, attributes: *mut FMOD_3D_ATTRIBUTES) -> FMOD_RESULT>;
pub type FMOD_DSP_GETUSERDATA_FUNC                    = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_DSP_DFT_FFTREAL_FUNC                    = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, size: ::core::ffi::c_int, signal: *const ::core::ffi::c_float, dft: *mut FMOD_COMPLEX, window: *const ::core::ffi::c_float, signalhop: ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_DSP_DFT_IFFTREAL_FUNC                   = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, size: ::core::ffi::c_int, dft: *const FMOD_COMPLEX, signal: *mut ::core::ffi::c_float, window: *const ::core::ffi::c_float, signalhop: ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_DSP_PAN_SUMMONOMATRIX_FUNC              = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, sourceSpeakerMode: FMOD_SPEAKERMODE, lowFrequencyGain: ::core::ffi::c_float, overallGain: ::core::ffi::c_float, matrix: *mut ::core::ffi::c_float) -> FMOD_RESULT>;
pub type FMOD_DSP_PAN_SUMSTEREOMATRIX_FUNC            = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, sourceSpeakerMode: FMOD_SPEAKERMODE, pan: ::core::ffi::c_float, lowFrequencyGain: ::core::ffi::c_float, overallGain: ::core::ffi::c_float, matrixHop: ::core::ffi::c_int, matrix: *mut ::core::ffi::c_float) -> FMOD_RESULT>;
pub type FMOD_DSP_PAN_SUMSURROUNDMATRIX_FUNC          = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, sourceSpeakerMode: FMOD_SPEAKERMODE, targetSpeakerMode: FMOD_SPEAKERMODE, direction: ::core::ffi::c_float, extent: ::core::ffi::c_float, rotation: ::core::ffi::c_float, lowFrequencyGain: ::core::ffi::c_float, overallGain: ::core::ffi::c_float, matrixHop: ::core::ffi::c_int, matrix: *mut ::core::ffi::c_float, flags: FMOD_DSP_PAN_SURROUND_FLAGS) -> FMOD_RESULT>;
pub type FMOD_DSP_PAN_SUMMONOTOSURROUNDMATRIX_FUNC    = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, targetSpeakerMode: FMOD_SPEAKERMODE, direction: ::core::ffi::c_float, extent: ::core::ffi::c_float, lowFrequencyGain: ::core::ffi::c_float, overallGain: ::core::ffi::c_float, matrixHop: ::core::ffi::c_int, matrix: *mut ::core::ffi::c_float) -> FMOD_RESULT>;
pub type FMOD_DSP_PAN_SUMSTEREOTOSURROUNDMATRIX_FUNC  = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, targetSpeakerMode: FMOD_SPEAKERMODE, direction: ::core::ffi::c_float, extent: ::core::ffi::c_float, rotation: ::core::ffi::c_float, lowFrequencyGain: ::core::ffi::c_float, overallGain: ::core::ffi::c_float, matrixHop: ::core::ffi::c_int, matrix: *mut ::core::ffi::c_float) -> FMOD_RESULT>;
pub type FMOD_DSP_PAN_GETROLLOFFGAIN_FUNC             = Option<unsafe extern "system" fn (dsp_state: *mut FMOD_DSP_STATE, rolloff: FMOD_DSP_PAN_3D_ROLLOFF_TYPE, distance: ::core::ffi::c_float, mindistance: ::core::ffi::c_float, maxdistance: ::core::ffi::c_float, gain: *mut ::core::ffi::c_float) -> FMOD_RESULT>;

/*
    DSP Structures
*/
#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_BUFFER_ARRAY {
    pub numbuffers: ::core::ffi::c_int,
    pub buffernumchannels: *mut ::core::ffi::c_int,
    pub bufferchannelmask: *mut FMOD_CHANNELMASK,
    pub buffers: *mut *mut ::core::ffi::c_float,
    pub speakermode: FMOD_SPEAKERMODE,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_COMPLEX {
    pub real: ::core::ffi::c_float,
    pub imag: ::core::ffi::c_float,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR {
    pub numpoints: ::core::ffi::c_int,
    pub pointparamvalues: *mut ::core::ffi::c_float,
    pub pointpositions: *mut ::core::ffi::c_float,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_FLOAT_MAPPING {
    pub r#type: FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE,
    pub piecewiselinearmapping: FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_DESC_FLOAT {
    pub min: ::core::ffi::c_float,
    pub max: ::core::ffi::c_float,
    pub defaultval: ::core::ffi::c_float,
    pub mapping: FMOD_DSP_PARAMETER_FLOAT_MAPPING,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_DESC_INT {
    pub min: ::core::ffi::c_int,
    pub max: ::core::ffi::c_int,
    pub defaultval: ::core::ffi::c_int,
    pub goestoinf: FMOD_BOOL,
    pub valuenames: *const *const ::core::ffi::c_char,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_DESC_BOOL {
    pub defaultval: FMOD_BOOL,
    pub valuenames: *const *const ::core::ffi::c_char,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_DESC_DATA {
    pub datatype: ::core::ffi::c_int,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_DESC {
    pub r#type: FMOD_DSP_PARAMETER_TYPE,
    pub name: [::core::ffi::c_char; (16) as usize],
    pub label: [::core::ffi::c_char; (16) as usize],
    pub description: *const ::core::ffi::c_char,

    pub value: FMOD_DSP_PARAMETER_DESC_VALUE,
}

#[repr(C)] #[derive(Copy, Clone)] pub union FMOD_DSP_PARAMETER_DESC_VALUE {
    pub floatdesc: FMOD_DSP_PARAMETER_DESC_FLOAT,
    pub intdesc: FMOD_DSP_PARAMETER_DESC_INT,
    pub booldesc: FMOD_DSP_PARAMETER_DESC_BOOL,
    pub datadesc: FMOD_DSP_PARAMETER_DESC_DATA,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_OVERALLGAIN {
    pub linear_gain: ::core::ffi::c_float,
    pub linear_gain_additive: ::core::ffi::c_float,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_3DATTRIBUTES {
    pub relative: FMOD_3D_ATTRIBUTES,
    pub absolute: FMOD_3D_ATTRIBUTES,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI {
    pub numlisteners: ::core::ffi::c_int,
    pub relative: [FMOD_3D_ATTRIBUTES; (FMOD_MAX_LISTENERS) as usize],
    pub weight: [::core::ffi::c_float; (FMOD_MAX_LISTENERS) as usize],
    pub absolute: FMOD_3D_ATTRIBUTES,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_ATTENUATION_RANGE {
    pub min: ::core::ffi::c_float,
    pub max: ::core::ffi::c_float,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_SIDECHAIN {
    pub sidechainenable: FMOD_BOOL,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_FFT {
    pub length: ::core::ffi::c_int,
    pub numchannels: ::core::ffi::c_int,
    pub spectrum: [*mut ::core::ffi::c_float; (32) as usize],
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_PARAMETER_DYNAMIC_RESPONSE {
    pub numchannels: ::core::ffi::c_int,
    pub rms: [::core::ffi::c_float; (32) as usize],
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_DESCRIPTION {
    pub pluginsdkversion: ::core::ffi::c_uint,
    pub name: [::core::ffi::c_char; (32) as usize],
    pub version: ::core::ffi::c_uint,
    pub numinputbuffers: ::core::ffi::c_int,
    pub numoutputbuffers: ::core::ffi::c_int,
    pub create: FMOD_DSP_CREATE_CALLBACK,
    pub release: FMOD_DSP_RELEASE_CALLBACK,
    pub reset: FMOD_DSP_RESET_CALLBACK,
    pub read: FMOD_DSP_READ_CALLBACK,
    pub process: FMOD_DSP_PROCESS_CALLBACK,
    pub setposition: FMOD_DSP_SETPOSITION_CALLBACK,

    pub numparameters: ::core::ffi::c_int,
    pub paramdesc: *mut *mut FMOD_DSP_PARAMETER_DESC,
    pub setparameterfloat: FMOD_DSP_SETPARAM_FLOAT_CALLBACK,
    pub setparameterint: FMOD_DSP_SETPARAM_INT_CALLBACK,
    pub setparameterbool: FMOD_DSP_SETPARAM_BOOL_CALLBACK,
    pub setparameterdata: FMOD_DSP_SETPARAM_DATA_CALLBACK,
    pub getparameterfloat: FMOD_DSP_GETPARAM_FLOAT_CALLBACK,
    pub getparameterint: FMOD_DSP_GETPARAM_INT_CALLBACK,
    pub getparameterbool: FMOD_DSP_GETPARAM_BOOL_CALLBACK,
    pub getparameterdata: FMOD_DSP_GETPARAM_DATA_CALLBACK,
    pub shouldiprocess: FMOD_DSP_SHOULDIPROCESS_CALLBACK,
    pub userdata: *mut ::core::ffi::c_void,

    pub sys_register: FMOD_DSP_SYSTEM_REGISTER_CALLBACK,
    pub sys_deregister: FMOD_DSP_SYSTEM_DEREGISTER_CALLBACK,
    pub sys_mix: FMOD_DSP_SYSTEM_MIX_CALLBACK,

}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_STATE_DFT_FUNCTIONS {
    pub fftreal: FMOD_DSP_DFT_FFTREAL_FUNC,
    pub inversefftreal: FMOD_DSP_DFT_IFFTREAL_FUNC,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_STATE_PAN_FUNCTIONS {
    pub summonomatrix: FMOD_DSP_PAN_SUMMONOMATRIX_FUNC,
    pub sumstereomatrix: FMOD_DSP_PAN_SUMSTEREOMATRIX_FUNC,
    pub sumsurroundmatrix: FMOD_DSP_PAN_SUMSURROUNDMATRIX_FUNC,
    pub summonotosurroundmatrix: FMOD_DSP_PAN_SUMMONOTOSURROUNDMATRIX_FUNC,
    pub sumstereotosurroundmatrix: FMOD_DSP_PAN_SUMSTEREOTOSURROUNDMATRIX_FUNC,
    pub getrolloffgain: FMOD_DSP_PAN_GETROLLOFFGAIN_FUNC,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_STATE_FUNCTIONS {
    pub alloc: FMOD_DSP_ALLOC_FUNC,
    pub realloc: FMOD_DSP_REALLOC_FUNC,
    pub free: FMOD_DSP_FREE_FUNC,
    pub getsamplerate: FMOD_DSP_GETSAMPLERATE_FUNC,
    pub getblocksize: FMOD_DSP_GETBLOCKSIZE_FUNC,
    pub dft: *mut FMOD_DSP_STATE_DFT_FUNCTIONS,
    pub pan: *mut FMOD_DSP_STATE_PAN_FUNCTIONS,
    pub getspeakermode: FMOD_DSP_GETSPEAKERMODE_FUNC,
    pub getclock: FMOD_DSP_GETCLOCK_FUNC,
    pub getlistenerattributes: FMOD_DSP_GETLISTENERATTRIBUTES_FUNC,
    pub log: FMOD_DSP_LOG_FUNC,
    pub getuserdata: FMOD_DSP_GETUSERDATA_FUNC,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_STATE {
    pub instance: *mut ::core::ffi::c_void,
    pub plugindata: *mut ::core::ffi::c_void,
    pub channelmask: FMOD_CHANNELMASK,
    pub source_speakermode: FMOD_SPEAKERMODE,
    pub sidechaindata: *mut ::core::ffi::c_float,
    pub sidechainchannels: ::core::ffi::c_int,
    pub functions: *mut FMOD_DSP_STATE_FUNCTIONS,
    pub systemobject: ::core::ffi::c_int,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_DSP_METERING_INFO {
    pub numsamples: ::core::ffi::c_int,
    pub peaklevel: [::core::ffi::c_float; (32) as usize],
    pub rmslevel: [::core::ffi::c_float; (32) as usize],
    pub numchannels: ::core::ffi::c_short,
}

/*
    DSP Macros
*/

