// @generated by carcinize.nu from FMOD headers
/* ======================================================================================== */
/* FMOD Core API - Codec development header file.                                           */
/* Copyright (c), Firelight Technologies Pty, Ltd. 2004-2025.                               */
/*                                                                                          */
/* Use this header if you are wanting to develop your own file format plugin to use with    */
/* FMOD's codec system.  With this header you can make your own fileformat plugin that FMOD */
/* can register and use.  See the documentation and examples on how to make a working       */
/* plugin.                                                                                  */
/*                                                                                          */
/* For more detail visit:                                                                   */
/* https://fmod.com/docs/2.03/api/core-api.html                                             */
/* ======================================================================================== */

/*
    Codec types
*/

/*
    Codec constants
*/
pub const FMOD_CODEC_PLUGIN_VERSION: ::core::ffi::c_int = 1;

pub const FMOD_CODEC_SEEK_METHOD_SET:      FMOD_CODEC_SEEK_METHOD = 0;
pub const FMOD_CODEC_SEEK_METHOD_CURRENT:  FMOD_CODEC_SEEK_METHOD = 1;
pub const FMOD_CODEC_SEEK_METHOD_END:      FMOD_CODEC_SEEK_METHOD = 2;
pub type FMOD_CODEC_SEEK_METHOD = ::core::ffi::c_int;

/*
    Codec callbacks
*/
pub type FMOD_CODEC_OPEN_CALLBACK          = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, usermode: FMOD_MODE, userexinfo: *mut FMOD_CREATESOUNDEXINFO) -> FMOD_RESULT>;
pub type FMOD_CODEC_CLOSE_CALLBACK         = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE) -> FMOD_RESULT>;
pub type FMOD_CODEC_READ_CALLBACK          = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, buffer: *mut ::core::ffi::c_void, samples_in: ::core::ffi::c_uint, samples_out: *mut ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_CODEC_GETLENGTH_CALLBACK     = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, length: *mut ::core::ffi::c_uint, lengthtype: FMOD_TIMEUNIT) -> FMOD_RESULT>;
pub type FMOD_CODEC_SETPOSITION_CALLBACK   = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, subsound: ::core::ffi::c_int, position: ::core::ffi::c_uint, postype: FMOD_TIMEUNIT) -> FMOD_RESULT>;
pub type FMOD_CODEC_GETPOSITION_CALLBACK   = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, position: *mut ::core::ffi::c_uint, postype: FMOD_TIMEUNIT) -> FMOD_RESULT>;
pub type FMOD_CODEC_SOUNDCREATE_CALLBACK   = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, subsound: ::core::ffi::c_int, sound: *mut FMOD_SOUND) -> FMOD_RESULT>;
pub type FMOD_CODEC_GETWAVEFORMAT_CALLBACK = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, index: ::core::ffi::c_int, waveformat: *mut FMOD_CODEC_WAVEFORMAT) -> FMOD_RESULT>;

/*
    Codec functions
*/
pub type FMOD_CODEC_METADATA_FUNC          = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, tagtype: FMOD_TAGTYPE, name: *mut ::core::ffi::c_char, data: *mut ::core::ffi::c_void, datalen: ::core::ffi::c_uint, datatype: FMOD_TAGDATATYPE, unique: ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_CODEC_ALLOC_FUNC             = Option<unsafe extern "system" fn (size: ::core::ffi::c_uint, align: ::core::ffi::c_uint, file: *const ::core::ffi::c_char, line: ::core::ffi::c_int) -> *mut ::core::ffi::c_void      >;
pub type FMOD_CODEC_FREE_FUNC              = Option<unsafe extern "system" fn (ptr: *mut ::core::ffi::c_void, file: *const ::core::ffi::c_char, line: ::core::ffi::c_int)>;
pub type FMOD_CODEC_LOG_FUNC               = unsafe extern "C" fn (level: FMOD_DEBUG_FLAGS, file: *const ::core::ffi::c_char, line: ::core::ffi::c_int, function: *const ::core::ffi::c_char, string: *const ::core::ffi::c_char, ...);

pub type FMOD_CODEC_FILE_READ_FUNC         = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, buffer: *mut ::core::ffi::c_void, sizebytes: ::core::ffi::c_uint, bytesread: *mut ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_CODEC_FILE_SEEK_FUNC         = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, pos: ::core::ffi::c_uint, method: FMOD_CODEC_SEEK_METHOD) -> FMOD_RESULT>;
pub type FMOD_CODEC_FILE_TELL_FUNC         = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, pos: *mut ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_CODEC_FILE_SIZE_FUNC         = Option<unsafe extern "system" fn (codec_state: *mut FMOD_CODEC_STATE, size: *mut ::core::ffi::c_uint) -> FMOD_RESULT>;

/*
    Codec structures
*/
#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_CODEC_DESCRIPTION {
    pub apiversion: ::core::ffi::c_uint,
    pub name: *const ::core::ffi::c_char,
    pub version: ::core::ffi::c_uint,
    pub defaultasstream: ::core::ffi::c_int,
    pub timeunits: FMOD_TIMEUNIT,
    pub open: FMOD_CODEC_OPEN_CALLBACK,
    pub close: FMOD_CODEC_CLOSE_CALLBACK,
    pub read: FMOD_CODEC_READ_CALLBACK,
    pub getlength: FMOD_CODEC_GETLENGTH_CALLBACK,
    pub setposition: FMOD_CODEC_SETPOSITION_CALLBACK,
    pub getposition: FMOD_CODEC_GETPOSITION_CALLBACK,
    pub soundcreate: FMOD_CODEC_SOUNDCREATE_CALLBACK,
    pub getwaveformat: FMOD_CODEC_GETWAVEFORMAT_CALLBACK,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_CODEC_WAVEFORMAT {
    pub name: *const ::core::ffi::c_char,
    pub format: FMOD_SOUND_FORMAT,
    pub channels: ::core::ffi::c_int,
    pub frequency: ::core::ffi::c_int,
    pub lengthbytes: ::core::ffi::c_uint,
    pub lengthpcm: ::core::ffi::c_uint,
    pub pcmblocksize: ::core::ffi::c_uint,
    pub loopstart: ::core::ffi::c_int,
    pub loopend: ::core::ffi::c_int,
    pub mode: FMOD_MODE,
    pub channelmask: FMOD_CHANNELMASK,
    pub channelorder: FMOD_CHANNELORDER,
    pub peakvolume: ::core::ffi::c_float,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_CODEC_STATE_FUNCTIONS {
    pub metadata: FMOD_CODEC_METADATA_FUNC,
    pub alloc: FMOD_CODEC_ALLOC_FUNC,
    pub free: FMOD_CODEC_FREE_FUNC,
    pub log: FMOD_CODEC_LOG_FUNC,
    pub read: FMOD_CODEC_FILE_READ_FUNC,
    pub seek: FMOD_CODEC_FILE_SEEK_FUNC,
    pub tell: FMOD_CODEC_FILE_TELL_FUNC,
    pub size: FMOD_CODEC_FILE_SIZE_FUNC,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_CODEC_STATE {
    pub plugindata: *mut ::core::ffi::c_void,
    pub waveformat: *mut FMOD_CODEC_WAVEFORMAT,
    pub functions: *mut FMOD_CODEC_STATE_FUNCTIONS,
    pub numsubsounds: ::core::ffi::c_int,
}

/*
    Codec macros
*/


