// @generated by carcinize.nu from FMOD headers
/* ======================================================================================== */
/* FMOD Core API - C header file.                                                           */
/* Copyright (c), Firelight Technologies Pty, Ltd. 2004-2025.                               */
/*                                                                                          */
/* Use this header in conjunction with fmod_common.h (which contains all the constants /    */
/* callbacks) to develop using the C interface                                              */
/*                                                                                          */
/* For more detail visit:                                                                   */
/* https://fmod.com/docs/2.03/api/core-api.html                                             */
/* ======================================================================================== */
unsafe extern "system" {

/*
    FMOD global system functions (optional).
*/
pub unsafe fn FMOD_Memory_Initialize           (poolmem: *mut ::core::ffi::c_void, poollen: ::core::ffi::c_int, useralloc: FMOD_MEMORY_ALLOC_CALLBACK, userrealloc: FMOD_MEMORY_REALLOC_CALLBACK, userfree: FMOD_MEMORY_FREE_CALLBACK, memtypeflags: FMOD_MEMORY_TYPE) -> FMOD_RESULT;
pub unsafe fn FMOD_Memory_GetStats             (currentalloced: *mut ::core::ffi::c_int, maxalloced: *mut ::core::ffi::c_int, blocking: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Debug_Initialize            (flags: FMOD_DEBUG_FLAGS, mode: FMOD_DEBUG_MODE, callback: FMOD_DEBUG_CALLBACK, filename: *const ::core::ffi::c_char) -> FMOD_RESULT;
pub unsafe fn FMOD_File_SetDiskBusy            (busy: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_File_GetDiskBusy            (busy: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Thread_SetAttributes        (r#type: FMOD_THREAD_TYPE, affinity: FMOD_THREAD_AFFINITY, priority: FMOD_THREAD_PRIORITY, stacksize: FMOD_THREAD_STACK_SIZE) -> FMOD_RESULT;

/*
    FMOD System factory functions.  Use this to create an FMOD System Instance.  below you will see FMOD_System_Init/Close to get started.
*/
pub unsafe fn FMOD_System_Create               (system: *mut *mut FMOD_SYSTEM, headerversion: ::core::ffi::c_uint) -> FMOD_RESULT; 
pub unsafe fn FMOD_System_Release              (system: *mut FMOD_SYSTEM) -> FMOD_RESULT; 

/*
    'System' API
*/

/* Setup functions. */
pub unsafe fn FMOD_System_SetOutput                 (system: *mut FMOD_SYSTEM, output: FMOD_OUTPUTTYPE) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetOutput                 (system: *mut FMOD_SYSTEM, output: *mut FMOD_OUTPUTTYPE) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetNumDrivers             (system: *mut FMOD_SYSTEM, numdrivers: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetDriverInfo             (system: *mut FMOD_SYSTEM, id: ::core::ffi::c_int, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int, guid: *mut FMOD_GUID, systemrate: *mut ::core::ffi::c_int, speakermode: *mut FMOD_SPEAKERMODE, speakermodechannels: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetDriver                 (system: *mut FMOD_SYSTEM, driver: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetDriver                 (system: *mut FMOD_SYSTEM, driver: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetSoftwareChannels       (system: *mut FMOD_SYSTEM, numsoftwarechannels: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetSoftwareChannels       (system: *mut FMOD_SYSTEM, numsoftwarechannels: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetSoftwareFormat         (system: *mut FMOD_SYSTEM, samplerate: ::core::ffi::c_int, speakermode: FMOD_SPEAKERMODE, numrawspeakers: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetSoftwareFormat         (system: *mut FMOD_SYSTEM, samplerate: *mut ::core::ffi::c_int, speakermode: *mut FMOD_SPEAKERMODE, numrawspeakers: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetDSPBufferSize          (system: *mut FMOD_SYSTEM, bufferlength: ::core::ffi::c_uint, numbuffers: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetDSPBufferSize          (system: *mut FMOD_SYSTEM, bufferlength: *mut ::core::ffi::c_uint, numbuffers: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetFileSystem             (system: *mut FMOD_SYSTEM, useropen: FMOD_FILE_OPEN_CALLBACK, userclose: FMOD_FILE_CLOSE_CALLBACK, userread: FMOD_FILE_READ_CALLBACK, userseek: FMOD_FILE_SEEK_CALLBACK, userasyncread: FMOD_FILE_ASYNCREAD_CALLBACK, userasynccancel: FMOD_FILE_ASYNCCANCEL_CALLBACK, blockalign: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_AttachFileSystem          (system: *mut FMOD_SYSTEM, useropen: FMOD_FILE_OPEN_CALLBACK, userclose: FMOD_FILE_CLOSE_CALLBACK, userread: FMOD_FILE_READ_CALLBACK, userseek: FMOD_FILE_SEEK_CALLBACK) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetAdvancedSettings       (system: *mut FMOD_SYSTEM, settings: *mut FMOD_ADVANCEDSETTINGS) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetAdvancedSettings       (system: *mut FMOD_SYSTEM, settings: *mut FMOD_ADVANCEDSETTINGS) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetCallback               (system: *mut FMOD_SYSTEM, callback: FMOD_SYSTEM_CALLBACK, callbackmask: FMOD_SYSTEM_CALLBACK_TYPE) -> FMOD_RESULT;

/* Plug-in support. */
pub unsafe fn FMOD_System_SetPluginPath             (system: *mut FMOD_SYSTEM, path: *const ::core::ffi::c_char) -> FMOD_RESULT;
pub unsafe fn FMOD_System_LoadPlugin                (system: *mut FMOD_SYSTEM, filename: *const ::core::ffi::c_char, handle: *mut ::core::ffi::c_uint, priority: ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_UnloadPlugin              (system: *mut FMOD_SYSTEM, handle: ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetNumNestedPlugins       (system: *mut FMOD_SYSTEM, handle: ::core::ffi::c_uint, count: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetNestedPlugin           (system: *mut FMOD_SYSTEM, handle: ::core::ffi::c_uint, index: ::core::ffi::c_int, nestedhandle: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetNumPlugins             (system: *mut FMOD_SYSTEM, plugintype: FMOD_PLUGINTYPE, numplugins: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetPluginHandle           (system: *mut FMOD_SYSTEM, plugintype: FMOD_PLUGINTYPE, index: ::core::ffi::c_int, handle: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetPluginInfo             (system: *mut FMOD_SYSTEM, handle: ::core::ffi::c_uint, plugintype: *mut FMOD_PLUGINTYPE, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int, version: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetOutputByPlugin         (system: *mut FMOD_SYSTEM, handle: ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetOutputByPlugin         (system: *mut FMOD_SYSTEM, handle: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_CreateDSPByPlugin         (system: *mut FMOD_SYSTEM, handle: ::core::ffi::c_uint, dsp: *mut *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetDSPInfoByPlugin        (system: *mut FMOD_SYSTEM, handle: ::core::ffi::c_uint, description: *mut *const FMOD_DSP_DESCRIPTION) -> FMOD_RESULT;
pub unsafe fn FMOD_System_RegisterCodec             (system: *mut FMOD_SYSTEM, description: *mut FMOD_CODEC_DESCRIPTION, handle: *mut ::core::ffi::c_uint, priority: ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_RegisterDSP               (system: *mut FMOD_SYSTEM, description: *const FMOD_DSP_DESCRIPTION, handle: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_RegisterOutput            (system: *mut FMOD_SYSTEM, description: *const FMOD_OUTPUT_DESCRIPTION, handle: *mut ::core::ffi::c_uint) -> FMOD_RESULT;

/* Init/Close. */
pub unsafe fn FMOD_System_Init                      (system: *mut FMOD_SYSTEM, maxchannels: ::core::ffi::c_int, flags: FMOD_INITFLAGS, extradriverdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Close                     (system: *mut FMOD_SYSTEM) -> FMOD_RESULT;

/* General post-init system functions. */
pub unsafe fn FMOD_System_Update                    (system: *mut FMOD_SYSTEM) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetSpeakerPosition        (system: *mut FMOD_SYSTEM, speaker: FMOD_SPEAKER, x: ::core::ffi::c_float, y: ::core::ffi::c_float, active: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetSpeakerPosition        (system: *mut FMOD_SYSTEM, speaker: FMOD_SPEAKER, x: *mut ::core::ffi::c_float, y: *mut ::core::ffi::c_float, active: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetStreamBufferSize       (system: *mut FMOD_SYSTEM, filebuffersize: ::core::ffi::c_uint, filebuffersizetype: FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetStreamBufferSize       (system: *mut FMOD_SYSTEM, filebuffersize: *mut ::core::ffi::c_uint, filebuffersizetype: *mut FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Set3DSettings             (system: *mut FMOD_SYSTEM, dopplerscale: ::core::ffi::c_float, distancefactor: ::core::ffi::c_float, rolloffscale: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Get3DSettings             (system: *mut FMOD_SYSTEM, dopplerscale: *mut ::core::ffi::c_float, distancefactor: *mut ::core::ffi::c_float, rolloffscale: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Set3DNumListeners         (system: *mut FMOD_SYSTEM, numlisteners: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Get3DNumListeners         (system: *mut FMOD_SYSTEM, numlisteners: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Set3DListenerAttributes   (system: *mut FMOD_SYSTEM, listener: ::core::ffi::c_int, pos: *const FMOD_VECTOR, vel: *const FMOD_VECTOR, forward: *const FMOD_VECTOR, up: *const FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Get3DListenerAttributes   (system: *mut FMOD_SYSTEM, listener: ::core::ffi::c_int, pos: *mut FMOD_VECTOR, vel: *mut FMOD_VECTOR, forward: *mut FMOD_VECTOR, up: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_System_Set3DRolloffCallback      (system: *mut FMOD_SYSTEM, callback: FMOD_3D_ROLLOFF_CALLBACK) -> FMOD_RESULT;
pub unsafe fn FMOD_System_MixerSuspend              (system: *mut FMOD_SYSTEM) -> FMOD_RESULT;
pub unsafe fn FMOD_System_MixerResume               (system: *mut FMOD_SYSTEM) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetDefaultMixMatrix       (system: *mut FMOD_SYSTEM, sourcespeakermode: FMOD_SPEAKERMODE, targetspeakermode: FMOD_SPEAKERMODE, matrix: *mut ::core::ffi::c_float, matrixhop: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetSpeakerModeChannels    (system: *mut FMOD_SYSTEM, mode: FMOD_SPEAKERMODE, channels: *mut ::core::ffi::c_int) -> FMOD_RESULT;

/* System information functions. */
pub unsafe fn FMOD_System_GetVersion                (system: *mut FMOD_SYSTEM, version: *mut ::core::ffi::c_uint, buildnumber: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetOutputHandle           (system: *mut FMOD_SYSTEM, handle: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetChannelsPlaying        (system: *mut FMOD_SYSTEM, channels: *mut ::core::ffi::c_int, realchannels: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetCPUUsage               (system: *mut FMOD_SYSTEM, usage: *mut FMOD_CPU_USAGE) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetFileUsage              (system: *mut FMOD_SYSTEM, sampleBytesRead: *mut ::core::ffi::c_longlong, streamBytesRead: *mut ::core::ffi::c_longlong, otherBytesRead: *mut ::core::ffi::c_longlong) -> FMOD_RESULT;

/* Sound/DSP/Channel/FX creation and retrieval. */
pub unsafe fn FMOD_System_CreateSound               (system: *mut FMOD_SYSTEM, name_or_data: *const ::core::ffi::c_char, mode: FMOD_MODE, exinfo: *mut FMOD_CREATESOUNDEXINFO, sound: *mut *mut FMOD_SOUND) -> FMOD_RESULT;
pub unsafe fn FMOD_System_CreateStream              (system: *mut FMOD_SYSTEM, name_or_data: *const ::core::ffi::c_char, mode: FMOD_MODE, exinfo: *mut FMOD_CREATESOUNDEXINFO, sound: *mut *mut FMOD_SOUND) -> FMOD_RESULT;
pub unsafe fn FMOD_System_CreateDSP                 (system: *mut FMOD_SYSTEM, description: *const FMOD_DSP_DESCRIPTION, dsp: *mut *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_System_CreateDSPByType           (system: *mut FMOD_SYSTEM, r#type: FMOD_DSP_TYPE, dsp: *mut *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_System_CreateChannelGroup        (system: *mut FMOD_SYSTEM, name: *const ::core::ffi::c_char, channelgroup: *mut *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_System_CreateSoundGroup          (system: *mut FMOD_SYSTEM, name: *const ::core::ffi::c_char, soundgroup: *mut *mut FMOD_SOUNDGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_System_CreateReverb3D            (system: *mut FMOD_SYSTEM, reverb: *mut *mut FMOD_REVERB3D) -> FMOD_RESULT;
pub unsafe fn FMOD_System_PlaySound                 (system: *mut FMOD_SYSTEM, sound: *mut FMOD_SOUND, channelgroup: *mut FMOD_CHANNELGROUP, paused: FMOD_BOOL, channel: *mut *mut FMOD_CHANNEL) -> FMOD_RESULT;
pub unsafe fn FMOD_System_PlayDSP                   (system: *mut FMOD_SYSTEM, dsp: *mut FMOD_DSP, channelgroup: *mut FMOD_CHANNELGROUP, paused: FMOD_BOOL, channel: *mut *mut FMOD_CHANNEL) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetChannel                (system: *mut FMOD_SYSTEM, channelid: ::core::ffi::c_int, channel: *mut *mut FMOD_CHANNEL) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetDSPInfoByType          (system: *mut FMOD_SYSTEM, r#type: FMOD_DSP_TYPE, description: *mut *const FMOD_DSP_DESCRIPTION) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetMasterChannelGroup     (system: *mut FMOD_SYSTEM, channelgroup: *mut *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetMasterSoundGroup       (system: *mut FMOD_SYSTEM, soundgroup: *mut *mut FMOD_SOUNDGROUP) -> FMOD_RESULT;

/* Routing to ports. */
pub unsafe fn FMOD_System_AttachChannelGroupToPort  (system: *mut FMOD_SYSTEM, portType: FMOD_PORT_TYPE, portIndex: FMOD_PORT_INDEX, channelgroup: *mut FMOD_CHANNELGROUP, passThru: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_System_DetachChannelGroupFromPort(system: *mut FMOD_SYSTEM, channelgroup: *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;

/* Reverb API. */
pub unsafe fn FMOD_System_SetReverbProperties       (system: *mut FMOD_SYSTEM, instance: ::core::ffi::c_int, prop: *const FMOD_REVERB_PROPERTIES) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetReverbProperties       (system: *mut FMOD_SYSTEM, instance: ::core::ffi::c_int, prop: *mut FMOD_REVERB_PROPERTIES) -> FMOD_RESULT;

/* System level DSP functionality. */
pub unsafe fn FMOD_System_LockDSP                   (system: *mut FMOD_SYSTEM) -> FMOD_RESULT;
pub unsafe fn FMOD_System_UnlockDSP                 (system: *mut FMOD_SYSTEM) -> FMOD_RESULT;

/* Recording API. */
pub unsafe fn FMOD_System_GetRecordNumDrivers       (system: *mut FMOD_SYSTEM, numdrivers: *mut ::core::ffi::c_int, numconnected: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetRecordDriverInfo       (system: *mut FMOD_SYSTEM, id: ::core::ffi::c_int, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int, guid: *mut FMOD_GUID, systemrate: *mut ::core::ffi::c_int, speakermode: *mut FMOD_SPEAKERMODE, speakermodechannels: *mut ::core::ffi::c_int, state: *mut FMOD_DRIVER_STATE) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetRecordPosition         (system: *mut FMOD_SYSTEM, id: ::core::ffi::c_int, position: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_System_RecordStart               (system: *mut FMOD_SYSTEM, id: ::core::ffi::c_int, sound: *mut FMOD_SOUND, r#loop: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_System_RecordStop                (system: *mut FMOD_SYSTEM, id: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_IsRecording               (system: *mut FMOD_SYSTEM, id: ::core::ffi::c_int, recording: *mut FMOD_BOOL) -> FMOD_RESULT;

/* Geometry API. */
pub unsafe fn FMOD_System_CreateGeometry            (system: *mut FMOD_SYSTEM, maxpolygons: ::core::ffi::c_int, maxvertices: ::core::ffi::c_int, geometry: *mut *mut FMOD_GEOMETRY) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetGeometrySettings       (system: *mut FMOD_SYSTEM, maxworldsize: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetGeometrySettings       (system: *mut FMOD_SYSTEM, maxworldsize: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_System_LoadGeometry              (system: *mut FMOD_SYSTEM, data: *const ::core::ffi::c_void, datasize: ::core::ffi::c_int, geometry: *mut *mut FMOD_GEOMETRY) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetGeometryOcclusion      (system: *mut FMOD_SYSTEM, listener: *const FMOD_VECTOR, source: *const FMOD_VECTOR, direct: *mut ::core::ffi::c_float, reverb: *mut ::core::ffi::c_float) -> FMOD_RESULT;

/* Network functions. */
pub unsafe fn FMOD_System_SetNetworkProxy           (system: *mut FMOD_SYSTEM, proxy: *const ::core::ffi::c_char) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetNetworkProxy           (system: *mut FMOD_SYSTEM, proxy: *mut ::core::ffi::c_char, proxylen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_SetNetworkTimeout         (system: *mut FMOD_SYSTEM, timeout: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetNetworkTimeout         (system: *mut FMOD_SYSTEM, timeout: *mut ::core::ffi::c_int) -> FMOD_RESULT;

/* Userdata set/get. */
pub unsafe fn FMOD_System_SetUserData               (system: *mut FMOD_SYSTEM, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_System_GetUserData               (system: *mut FMOD_SYSTEM, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

/* Sound API
*/

pub unsafe fn FMOD_Sound_Release                    (sound: *mut FMOD_SOUND) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetSystemObject            (sound: *mut FMOD_SOUND, system: *mut *mut FMOD_SYSTEM) -> FMOD_RESULT;

/*
     Standard sound manipulation functions.
*/

pub unsafe fn FMOD_Sound_Lock                       (sound: *mut FMOD_SOUND, offset: ::core::ffi::c_uint, length: ::core::ffi::c_uint, ptr1: *mut *mut ::core::ffi::c_void, ptr2: *mut *mut ::core::ffi::c_void, len1: *mut ::core::ffi::c_uint, len2: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_Unlock                     (sound: *mut FMOD_SOUND, ptr1: *mut ::core::ffi::c_void, ptr2: *mut ::core::ffi::c_void, len1: ::core::ffi::c_uint, len2: ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_SetDefaults                (sound: *mut FMOD_SOUND, frequency: ::core::ffi::c_float, priority: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetDefaults                (sound: *mut FMOD_SOUND, frequency: *mut ::core::ffi::c_float, priority: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_Set3DMinMaxDistance        (sound: *mut FMOD_SOUND, min: ::core::ffi::c_float, max: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_Get3DMinMaxDistance        (sound: *mut FMOD_SOUND, min: *mut ::core::ffi::c_float, max: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_Set3DConeSettings          (sound: *mut FMOD_SOUND, insideconeangle: ::core::ffi::c_float, outsideconeangle: ::core::ffi::c_float, outsidevolume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_Get3DConeSettings          (sound: *mut FMOD_SOUND, insideconeangle: *mut ::core::ffi::c_float, outsideconeangle: *mut ::core::ffi::c_float, outsidevolume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_Set3DCustomRolloff         (sound: *mut FMOD_SOUND, points: *mut FMOD_VECTOR, numpoints: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_Get3DCustomRolloff         (sound: *mut FMOD_SOUND, points: *mut *mut FMOD_VECTOR, numpoints: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetSubSound                (sound: *mut FMOD_SOUND, index: ::core::ffi::c_int, subsound: *mut *mut FMOD_SOUND) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetSubSoundParent          (sound: *mut FMOD_SOUND, parentsound: *mut *mut FMOD_SOUND) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetName                    (sound: *mut FMOD_SOUND, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetLength                  (sound: *mut FMOD_SOUND, length: *mut ::core::ffi::c_uint, lengthtype: FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetFormat                  (sound: *mut FMOD_SOUND, r#type: *mut FMOD_SOUND_TYPE, format: *mut FMOD_SOUND_FORMAT, channels: *mut ::core::ffi::c_int, bits: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetNumSubSounds            (sound: *mut FMOD_SOUND, numsubsounds: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetNumTags                 (sound: *mut FMOD_SOUND, numtags: *mut ::core::ffi::c_int, numtagsupdated: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetTag                     (sound: *mut FMOD_SOUND, name: *const ::core::ffi::c_char, index: ::core::ffi::c_int, tag: *mut FMOD_TAG) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetOpenState               (sound: *mut FMOD_SOUND, openstate: *mut FMOD_OPENSTATE, percentbuffered: *mut ::core::ffi::c_uint, starving: *mut FMOD_BOOL, diskbusy: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_ReadData                   (sound: *mut FMOD_SOUND, buffer: *mut ::core::ffi::c_void, length: ::core::ffi::c_uint, read: *mut ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_SeekData                   (sound: *mut FMOD_SOUND, pcm: ::core::ffi::c_uint) -> FMOD_RESULT;

pub unsafe fn FMOD_Sound_SetSoundGroup              (sound: *mut FMOD_SOUND, soundgroup: *mut FMOD_SOUNDGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetSoundGroup              (sound: *mut FMOD_SOUND, soundgroup: *mut *mut FMOD_SOUNDGROUP) -> FMOD_RESULT;

/*
     Synchronization point API.  These points can come from markers embedded in wav files, and can also generate channel callbacks.
*/

pub unsafe fn FMOD_Sound_GetNumSyncPoints           (sound: *mut FMOD_SOUND, numsyncpoints: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetSyncPoint               (sound: *mut FMOD_SOUND, index: ::core::ffi::c_int, point: *mut *mut FMOD_SYNCPOINT) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetSyncPointInfo           (sound: *mut FMOD_SOUND, point: *mut FMOD_SYNCPOINT, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int, offset: *mut ::core::ffi::c_uint, offsettype: FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_AddSyncPoint               (sound: *mut FMOD_SOUND, offset: ::core::ffi::c_uint, offsettype: FMOD_TIMEUNIT, name: *const ::core::ffi::c_char, point: *mut *mut FMOD_SYNCPOINT) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_DeleteSyncPoint            (sound: *mut FMOD_SOUND, point: *mut FMOD_SYNCPOINT) -> FMOD_RESULT;

/*
     Functions also in Channel class but here they are the 'default' to save having to change it in Channel all the time.
*/

pub unsafe fn FMOD_Sound_SetMode                    (sound: *mut FMOD_SOUND, mode: FMOD_MODE) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetMode                    (sound: *mut FMOD_SOUND, mode: *mut FMOD_MODE) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_SetLoopCount               (sound: *mut FMOD_SOUND, loopcount: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetLoopCount               (sound: *mut FMOD_SOUND, loopcount: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_SetLoopPoints              (sound: *mut FMOD_SOUND, loopstart: ::core::ffi::c_uint, loopstarttype: FMOD_TIMEUNIT, loopend: ::core::ffi::c_uint, loopendtype: FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetLoopPoints              (sound: *mut FMOD_SOUND, loopstart: *mut ::core::ffi::c_uint, loopstarttype: FMOD_TIMEUNIT, loopend: *mut ::core::ffi::c_uint, loopendtype: FMOD_TIMEUNIT) -> FMOD_RESULT;

/*
     For MOD/S3M/XM/IT/MID sequenced formats only.
*/

pub unsafe fn FMOD_Sound_GetMusicNumChannels        (sound: *mut FMOD_SOUND, numchannels: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_SetMusicChannelVolume      (sound: *mut FMOD_SOUND, channel: ::core::ffi::c_int, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetMusicChannelVolume      (sound: *mut FMOD_SOUND, channel: ::core::ffi::c_int, volume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_SetMusicSpeed              (sound: *mut FMOD_SOUND, speed: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetMusicSpeed              (sound: *mut FMOD_SOUND, speed: *mut ::core::ffi::c_float) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_Sound_SetUserData                (sound: *mut FMOD_SOUND, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_Sound_GetUserData                (sound: *mut FMOD_SOUND, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

/*
    'Channel' API
*/

pub unsafe fn FMOD_Channel_GetSystemObject          (channel: *mut FMOD_CHANNEL, system: *mut *mut FMOD_SYSTEM) -> FMOD_RESULT;

/*
     General control functionality for Channels and ChannelGroups.
*/

pub unsafe fn FMOD_Channel_Stop                     (channel: *mut FMOD_CHANNEL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetPaused                (channel: *mut FMOD_CHANNEL, paused: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetPaused                (channel: *mut FMOD_CHANNEL, paused: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetVolume                (channel: *mut FMOD_CHANNEL, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetVolume                (channel: *mut FMOD_CHANNEL, volume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetVolumeRamp            (channel: *mut FMOD_CHANNEL, ramp: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetVolumeRamp            (channel: *mut FMOD_CHANNEL, ramp: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetAudibility            (channel: *mut FMOD_CHANNEL, audibility: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetPitch                 (channel: *mut FMOD_CHANNEL, pitch: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetPitch                 (channel: *mut FMOD_CHANNEL, pitch: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetMute                  (channel: *mut FMOD_CHANNEL, mute: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetMute                  (channel: *mut FMOD_CHANNEL, mute: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetReverbProperties      (channel: *mut FMOD_CHANNEL, instance: ::core::ffi::c_int, wet: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetReverbProperties      (channel: *mut FMOD_CHANNEL, instance: ::core::ffi::c_int, wet: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetLowPassGain           (channel: *mut FMOD_CHANNEL, gain: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetLowPassGain           (channel: *mut FMOD_CHANNEL, gain: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetMode                  (channel: *mut FMOD_CHANNEL, mode: FMOD_MODE) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetMode                  (channel: *mut FMOD_CHANNEL, mode: *mut FMOD_MODE) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetCallback              (channel: *mut FMOD_CHANNEL, callback: FMOD_CHANNELCONTROL_CALLBACK) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_IsPlaying                (channel: *mut FMOD_CHANNEL, isplaying: *mut FMOD_BOOL) -> FMOD_RESULT;

/*
     Note all 'set' functions alter a final matrix, getMixMatrix: this is why the only get function is, to avoid other get functions returning incorrect/obsolete values.
*/

pub unsafe fn FMOD_Channel_SetPan                   (channel: *mut FMOD_CHANNEL, pan: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetMixLevelsOutput       (channel: *mut FMOD_CHANNEL, frontleft: ::core::ffi::c_float, frontright: ::core::ffi::c_float, center: ::core::ffi::c_float, lfe: ::core::ffi::c_float, surroundleft: ::core::ffi::c_float, surroundright: ::core::ffi::c_float, backleft: ::core::ffi::c_float, backright: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetMixLevelsInput        (channel: *mut FMOD_CHANNEL, levels: *mut ::core::ffi::c_float, numlevels: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetMixMatrix             (channel: *mut FMOD_CHANNEL, matrix: *mut ::core::ffi::c_float, outchannels: ::core::ffi::c_int, inchannels: ::core::ffi::c_int, inchannel_hop: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetMixMatrix             (channel: *mut FMOD_CHANNEL, matrix: *mut ::core::ffi::c_float, outchannels: *mut ::core::ffi::c_int, inchannels: *mut ::core::ffi::c_int, inchannel_hop: ::core::ffi::c_int) -> FMOD_RESULT;

/*
     Clock based functionality.
*/

pub unsafe fn FMOD_Channel_GetDSPClock              (channel: *mut FMOD_CHANNEL, dspclock: *mut ::core::ffi::c_ulonglong, parentclock: *mut ::core::ffi::c_ulonglong) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetDelay                 (channel: *mut FMOD_CHANNEL, dspclock_start: ::core::ffi::c_ulonglong, dspclock_end: ::core::ffi::c_ulonglong, stopchannels: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetDelay                 (channel: *mut FMOD_CHANNEL, dspclock_start: *mut ::core::ffi::c_ulonglong, dspclock_end: *mut ::core::ffi::c_ulonglong, stopchannels: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_AddFadePoint             (channel: *mut FMOD_CHANNEL, dspclock: ::core::ffi::c_ulonglong, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetFadePointRamp         (channel: *mut FMOD_CHANNEL, dspclock: ::core::ffi::c_ulonglong, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_RemoveFadePoints         (channel: *mut FMOD_CHANNEL, dspclock_start: ::core::ffi::c_ulonglong, dspclock_end: ::core::ffi::c_ulonglong) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetFadePoints            (channel: *mut FMOD_CHANNEL, numpoints: *mut ::core::ffi::c_uint, point_dspclock: *mut ::core::ffi::c_ulonglong, point_volume: *mut ::core::ffi::c_float) -> FMOD_RESULT;

/*
     DSP effects.
*/

pub unsafe fn FMOD_Channel_GetDSP                   (channel: *mut FMOD_CHANNEL, index: ::core::ffi::c_int, dsp: *mut *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_AddDSP                   (channel: *mut FMOD_CHANNEL, index: ::core::ffi::c_int, dsp: *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_RemoveDSP                (channel: *mut FMOD_CHANNEL, dsp: *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetNumDSPs               (channel: *mut FMOD_CHANNEL, numdsps: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetDSPIndex              (channel: *mut FMOD_CHANNEL, dsp: *mut FMOD_DSP, index: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetDSPIndex              (channel: *mut FMOD_CHANNEL, dsp: *mut FMOD_DSP, index: *mut ::core::ffi::c_int) -> FMOD_RESULT;

/*
     3D functionality.
*/

pub unsafe fn FMOD_Channel_Set3DAttributes          (channel: *mut FMOD_CHANNEL, pos: *const FMOD_VECTOR, vel: *const FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DAttributes          (channel: *mut FMOD_CHANNEL, pos: *mut FMOD_VECTOR, vel: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DMinMaxDistance      (channel: *mut FMOD_CHANNEL, mindistance: ::core::ffi::c_float, maxdistance: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DMinMaxDistance      (channel: *mut FMOD_CHANNEL, mindistance: *mut ::core::ffi::c_float, maxdistance: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DConeSettings        (channel: *mut FMOD_CHANNEL, insideconeangle: ::core::ffi::c_float, outsideconeangle: ::core::ffi::c_float, outsidevolume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DConeSettings        (channel: *mut FMOD_CHANNEL, insideconeangle: *mut ::core::ffi::c_float, outsideconeangle: *mut ::core::ffi::c_float, outsidevolume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DConeOrientation     (channel: *mut FMOD_CHANNEL, orientation: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DConeOrientation     (channel: *mut FMOD_CHANNEL, orientation: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DCustomRolloff       (channel: *mut FMOD_CHANNEL, points: *mut FMOD_VECTOR, numpoints: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DCustomRolloff       (channel: *mut FMOD_CHANNEL, points: *mut *mut FMOD_VECTOR, numpoints: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DOcclusion           (channel: *mut FMOD_CHANNEL, directocclusion: ::core::ffi::c_float, reverbocclusion: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DOcclusion           (channel: *mut FMOD_CHANNEL, directocclusion: *mut ::core::ffi::c_float, reverbocclusion: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DSpread              (channel: *mut FMOD_CHANNEL, angle: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DSpread              (channel: *mut FMOD_CHANNEL, angle: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DLevel               (channel: *mut FMOD_CHANNEL, level: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DLevel               (channel: *mut FMOD_CHANNEL, level: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DDopplerLevel        (channel: *mut FMOD_CHANNEL, level: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DDopplerLevel        (channel: *mut FMOD_CHANNEL, level: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Set3DDistanceFilter      (channel: *mut FMOD_CHANNEL, custom: FMOD_BOOL, customLevel: ::core::ffi::c_float, centerFreq: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_Get3DDistanceFilter      (channel: *mut FMOD_CHANNEL, custom: *mut FMOD_BOOL, customLevel: *mut ::core::ffi::c_float, centerFreq: *mut ::core::ffi::c_float) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_Channel_SetUserData              (channel: *mut FMOD_CHANNEL, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetUserData              (channel: *mut FMOD_CHANNEL, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

/*
     Channel specific control functionality.
*/

pub unsafe fn FMOD_Channel_SetFrequency             (channel: *mut FMOD_CHANNEL, frequency: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetFrequency             (channel: *mut FMOD_CHANNEL, frequency: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetPriority              (channel: *mut FMOD_CHANNEL, priority: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetPriority              (channel: *mut FMOD_CHANNEL, priority: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetPosition              (channel: *mut FMOD_CHANNEL, position: ::core::ffi::c_uint, postype: FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetPosition              (channel: *mut FMOD_CHANNEL, position: *mut ::core::ffi::c_uint, postype: FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetChannelGroup          (channel: *mut FMOD_CHANNEL, channelgroup: *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetChannelGroup          (channel: *mut FMOD_CHANNEL, channelgroup: *mut *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetLoopCount             (channel: *mut FMOD_CHANNEL, loopcount: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetLoopCount             (channel: *mut FMOD_CHANNEL, loopcount: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_SetLoopPoints            (channel: *mut FMOD_CHANNEL, loopstart: ::core::ffi::c_uint, loopstarttype: FMOD_TIMEUNIT, loopend: ::core::ffi::c_uint, loopendtype: FMOD_TIMEUNIT) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetLoopPoints            (channel: *mut FMOD_CHANNEL, loopstart: *mut ::core::ffi::c_uint, loopstarttype: FMOD_TIMEUNIT, loopend: *mut ::core::ffi::c_uint, loopendtype: FMOD_TIMEUNIT) -> FMOD_RESULT;

/*
     Information only functions.
*/

pub unsafe fn FMOD_Channel_IsVirtual                (channel: *mut FMOD_CHANNEL, isvirtual: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetCurrentSound          (channel: *mut FMOD_CHANNEL, sound: *mut *mut FMOD_SOUND) -> FMOD_RESULT;
pub unsafe fn FMOD_Channel_GetIndex                 (channel: *mut FMOD_CHANNEL, index: *mut ::core::ffi::c_int) -> FMOD_RESULT;

/*
    'ChannelGroup' API
*/

pub unsafe fn FMOD_ChannelGroup_GetSystemObject     (channelgroup: *mut FMOD_CHANNELGROUP, system: *mut *mut FMOD_SYSTEM) -> FMOD_RESULT;

/*
     General control functionality for Channels and ChannelGroups.
*/

pub unsafe fn FMOD_ChannelGroup_Stop                (channelgroup: *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetPaused           (channelgroup: *mut FMOD_CHANNELGROUP, paused: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetPaused           (channelgroup: *mut FMOD_CHANNELGROUP, paused: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetVolume           (channelgroup: *mut FMOD_CHANNELGROUP, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetVolume           (channelgroup: *mut FMOD_CHANNELGROUP, volume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetVolumeRamp       (channelgroup: *mut FMOD_CHANNELGROUP, ramp: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetVolumeRamp       (channelgroup: *mut FMOD_CHANNELGROUP, ramp: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetAudibility       (channelgroup: *mut FMOD_CHANNELGROUP, audibility: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetPitch            (channelgroup: *mut FMOD_CHANNELGROUP, pitch: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetPitch            (channelgroup: *mut FMOD_CHANNELGROUP, pitch: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetMute             (channelgroup: *mut FMOD_CHANNELGROUP, mute: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetMute             (channelgroup: *mut FMOD_CHANNELGROUP, mute: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetReverbProperties (channelgroup: *mut FMOD_CHANNELGROUP, instance: ::core::ffi::c_int, wet: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetReverbProperties (channelgroup: *mut FMOD_CHANNELGROUP, instance: ::core::ffi::c_int, wet: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetLowPassGain      (channelgroup: *mut FMOD_CHANNELGROUP, gain: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetLowPassGain      (channelgroup: *mut FMOD_CHANNELGROUP, gain: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetMode             (channelgroup: *mut FMOD_CHANNELGROUP, mode: FMOD_MODE) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetMode             (channelgroup: *mut FMOD_CHANNELGROUP, mode: *mut FMOD_MODE) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetCallback         (channelgroup: *mut FMOD_CHANNELGROUP, callback: FMOD_CHANNELCONTROL_CALLBACK) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_IsPlaying           (channelgroup: *mut FMOD_CHANNELGROUP, isplaying: *mut FMOD_BOOL) -> FMOD_RESULT;

/*
     Note all 'set' functions alter a final matrix, getMixMatrix: this is why the only get function is, to avoid other get functions returning incorrect/obsolete values.
*/

pub unsafe fn FMOD_ChannelGroup_SetPan              (channelgroup: *mut FMOD_CHANNELGROUP, pan: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetMixLevelsOutput  (channelgroup: *mut FMOD_CHANNELGROUP, frontleft: ::core::ffi::c_float, frontright: ::core::ffi::c_float, center: ::core::ffi::c_float, lfe: ::core::ffi::c_float, surroundleft: ::core::ffi::c_float, surroundright: ::core::ffi::c_float, backleft: ::core::ffi::c_float, backright: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetMixLevelsInput   (channelgroup: *mut FMOD_CHANNELGROUP, levels: *mut ::core::ffi::c_float, numlevels: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetMixMatrix        (channelgroup: *mut FMOD_CHANNELGROUP, matrix: *mut ::core::ffi::c_float, outchannels: ::core::ffi::c_int, inchannels: ::core::ffi::c_int, inchannel_hop: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetMixMatrix        (channelgroup: *mut FMOD_CHANNELGROUP, matrix: *mut ::core::ffi::c_float, outchannels: *mut ::core::ffi::c_int, inchannels: *mut ::core::ffi::c_int, inchannel_hop: ::core::ffi::c_int) -> FMOD_RESULT;

/*
     Clock based functionality.
*/

pub unsafe fn FMOD_ChannelGroup_GetDSPClock         (channelgroup: *mut FMOD_CHANNELGROUP, dspclock: *mut ::core::ffi::c_ulonglong, parentclock: *mut ::core::ffi::c_ulonglong) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetDelay            (channelgroup: *mut FMOD_CHANNELGROUP, dspclock_start: ::core::ffi::c_ulonglong, dspclock_end: ::core::ffi::c_ulonglong, stopchannels: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetDelay            (channelgroup: *mut FMOD_CHANNELGROUP, dspclock_start: *mut ::core::ffi::c_ulonglong, dspclock_end: *mut ::core::ffi::c_ulonglong, stopchannels: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_AddFadePoint        (channelgroup: *mut FMOD_CHANNELGROUP, dspclock: ::core::ffi::c_ulonglong, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetFadePointRamp    (channelgroup: *mut FMOD_CHANNELGROUP, dspclock: ::core::ffi::c_ulonglong, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_RemoveFadePoints    (channelgroup: *mut FMOD_CHANNELGROUP, dspclock_start: ::core::ffi::c_ulonglong, dspclock_end: ::core::ffi::c_ulonglong) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetFadePoints       (channelgroup: *mut FMOD_CHANNELGROUP, numpoints: *mut ::core::ffi::c_uint, point_dspclock: *mut ::core::ffi::c_ulonglong, point_volume: *mut ::core::ffi::c_float) -> FMOD_RESULT;

/*
     DSP effects.
*/

pub unsafe fn FMOD_ChannelGroup_GetDSP              (channelgroup: *mut FMOD_CHANNELGROUP, index: ::core::ffi::c_int, dsp: *mut *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_AddDSP              (channelgroup: *mut FMOD_CHANNELGROUP, index: ::core::ffi::c_int, dsp: *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_RemoveDSP           (channelgroup: *mut FMOD_CHANNELGROUP, dsp: *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetNumDSPs          (channelgroup: *mut FMOD_CHANNELGROUP, numdsps: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_SetDSPIndex         (channelgroup: *mut FMOD_CHANNELGROUP, dsp: *mut FMOD_DSP, index: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetDSPIndex         (channelgroup: *mut FMOD_CHANNELGROUP, dsp: *mut FMOD_DSP, index: *mut ::core::ffi::c_int) -> FMOD_RESULT;

/*
     3D functionality.
*/

pub unsafe fn FMOD_ChannelGroup_Set3DAttributes     (channelgroup: *mut FMOD_CHANNELGROUP, pos: *const FMOD_VECTOR, vel: *const FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DAttributes     (channelgroup: *mut FMOD_CHANNELGROUP, pos: *mut FMOD_VECTOR, vel: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DMinMaxDistance (channelgroup: *mut FMOD_CHANNELGROUP, mindistance: ::core::ffi::c_float, maxdistance: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DMinMaxDistance (channelgroup: *mut FMOD_CHANNELGROUP, mindistance: *mut ::core::ffi::c_float, maxdistance: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DConeSettings   (channelgroup: *mut FMOD_CHANNELGROUP, insideconeangle: ::core::ffi::c_float, outsideconeangle: ::core::ffi::c_float, outsidevolume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DConeSettings   (channelgroup: *mut FMOD_CHANNELGROUP, insideconeangle: *mut ::core::ffi::c_float, outsideconeangle: *mut ::core::ffi::c_float, outsidevolume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DConeOrientation(channelgroup: *mut FMOD_CHANNELGROUP, orientation: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DConeOrientation(channelgroup: *mut FMOD_CHANNELGROUP, orientation: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DCustomRolloff  (channelgroup: *mut FMOD_CHANNELGROUP, points: *mut FMOD_VECTOR, numpoints: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DCustomRolloff  (channelgroup: *mut FMOD_CHANNELGROUP, points: *mut *mut FMOD_VECTOR, numpoints: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DOcclusion      (channelgroup: *mut FMOD_CHANNELGROUP, directocclusion: ::core::ffi::c_float, reverbocclusion: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DOcclusion      (channelgroup: *mut FMOD_CHANNELGROUP, directocclusion: *mut ::core::ffi::c_float, reverbocclusion: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DSpread         (channelgroup: *mut FMOD_CHANNELGROUP, angle: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DSpread         (channelgroup: *mut FMOD_CHANNELGROUP, angle: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DLevel          (channelgroup: *mut FMOD_CHANNELGROUP, level: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DLevel          (channelgroup: *mut FMOD_CHANNELGROUP, level: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DDopplerLevel   (channelgroup: *mut FMOD_CHANNELGROUP, level: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DDopplerLevel   (channelgroup: *mut FMOD_CHANNELGROUP, level: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Set3DDistanceFilter (channelgroup: *mut FMOD_CHANNELGROUP, custom: FMOD_BOOL, customLevel: ::core::ffi::c_float, centerFreq: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_Get3DDistanceFilter (channelgroup: *mut FMOD_CHANNELGROUP, custom: *mut FMOD_BOOL, customLevel: *mut ::core::ffi::c_float, centerFreq: *mut ::core::ffi::c_float) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_ChannelGroup_SetUserData         (channelgroup: *mut FMOD_CHANNELGROUP, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetUserData         (channelgroup: *mut FMOD_CHANNELGROUP, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

pub unsafe fn FMOD_ChannelGroup_Release             (channelgroup: *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;

/*
     Nested channel groups.
*/

pub unsafe fn FMOD_ChannelGroup_AddGroup            (channelgroup: *mut FMOD_CHANNELGROUP, group: *mut FMOD_CHANNELGROUP, propagatedspclock: FMOD_BOOL, connection: *mut *mut FMOD_DSPCONNECTION) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetNumGroups        (channelgroup: *mut FMOD_CHANNELGROUP, numgroups: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetGroup            (channelgroup: *mut FMOD_CHANNELGROUP, index: ::core::ffi::c_int, group: *mut *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetParentGroup      (channelgroup: *mut FMOD_CHANNELGROUP, group: *mut *mut FMOD_CHANNELGROUP) -> FMOD_RESULT;

/*
     Information only functions.
*/

pub unsafe fn FMOD_ChannelGroup_GetName             (channelgroup: *mut FMOD_CHANNELGROUP, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetNumChannels      (channelgroup: *mut FMOD_CHANNELGROUP, numchannels: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_ChannelGroup_GetChannel          (channelgroup: *mut FMOD_CHANNELGROUP, index: ::core::ffi::c_int, channel: *mut *mut FMOD_CHANNEL) -> FMOD_RESULT;

/*
    'SoundGroup' API
*/

pub unsafe fn FMOD_SoundGroup_Release               (soundgroup: *mut FMOD_SOUNDGROUP) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetSystemObject       (soundgroup: *mut FMOD_SOUNDGROUP, system: *mut *mut FMOD_SYSTEM) -> FMOD_RESULT;

/*
     SoundGroup control functions.
*/

pub unsafe fn FMOD_SoundGroup_SetMaxAudible         (soundgroup: *mut FMOD_SOUNDGROUP, maxaudible: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetMaxAudible         (soundgroup: *mut FMOD_SOUNDGROUP, maxaudible: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_SetMaxAudibleBehavior (soundgroup: *mut FMOD_SOUNDGROUP, behavior: FMOD_SOUNDGROUP_BEHAVIOR) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetMaxAudibleBehavior (soundgroup: *mut FMOD_SOUNDGROUP, behavior: *mut FMOD_SOUNDGROUP_BEHAVIOR) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_SetMuteFadeSpeed      (soundgroup: *mut FMOD_SOUNDGROUP, speed: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetMuteFadeSpeed      (soundgroup: *mut FMOD_SOUNDGROUP, speed: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_SetVolume             (soundgroup: *mut FMOD_SOUNDGROUP, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetVolume             (soundgroup: *mut FMOD_SOUNDGROUP, volume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_Stop                  (soundgroup: *mut FMOD_SOUNDGROUP) -> FMOD_RESULT;

/*
     Information only functions.
*/

pub unsafe fn FMOD_SoundGroup_GetName               (soundgroup: *mut FMOD_SOUNDGROUP, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetNumSounds          (soundgroup: *mut FMOD_SOUNDGROUP, numsounds: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetSound              (soundgroup: *mut FMOD_SOUNDGROUP, index: ::core::ffi::c_int, sound: *mut *mut FMOD_SOUND) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetNumPlaying         (soundgroup: *mut FMOD_SOUNDGROUP, numplaying: *mut ::core::ffi::c_int) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_SoundGroup_SetUserData           (soundgroup: *mut FMOD_SOUNDGROUP, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_SoundGroup_GetUserData           (soundgroup: *mut FMOD_SOUNDGROUP, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

/*
    'DSP' API
*/

pub unsafe fn FMOD_DSP_Release                      (dsp: *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetSystemObject              (dsp: *mut FMOD_DSP, system: *mut *mut FMOD_SYSTEM) -> FMOD_RESULT;

/*
     Connection / disconnection / input and output enumeration.
*/

pub unsafe fn FMOD_DSP_AddInput                     (dsp: *mut FMOD_DSP, input: *mut FMOD_DSP, connection: *mut *mut FMOD_DSPCONNECTION, r#type: FMOD_DSPCONNECTION_TYPE) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_DisconnectFrom               (dsp: *mut FMOD_DSP, target: *mut FMOD_DSP, connection: *mut FMOD_DSPCONNECTION) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_DisconnectAll                (dsp: *mut FMOD_DSP, inputs: FMOD_BOOL, outputs: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetNumInputs                 (dsp: *mut FMOD_DSP, numinputs: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetNumOutputs                (dsp: *mut FMOD_DSP, numoutputs: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetInput                     (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, input: *mut *mut FMOD_DSP, inputconnection: *mut *mut FMOD_DSPCONNECTION) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetOutput                    (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, output: *mut *mut FMOD_DSP, outputconnection: *mut *mut FMOD_DSPCONNECTION) -> FMOD_RESULT;

/*
     DSP unit control.
*/

pub unsafe fn FMOD_DSP_SetActive                    (dsp: *mut FMOD_DSP, active: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetActive                    (dsp: *mut FMOD_DSP, active: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_SetBypass                    (dsp: *mut FMOD_DSP, bypass: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetBypass                    (dsp: *mut FMOD_DSP, bypass: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_SetWetDryMix                 (dsp: *mut FMOD_DSP, prewet: ::core::ffi::c_float, postwet: ::core::ffi::c_float, dry: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetWetDryMix                 (dsp: *mut FMOD_DSP, prewet: *mut ::core::ffi::c_float, postwet: *mut ::core::ffi::c_float, dry: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_SetChannelFormat             (dsp: *mut FMOD_DSP, channelmask: FMOD_CHANNELMASK, numchannels: ::core::ffi::c_int, source_speakermode: FMOD_SPEAKERMODE) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetChannelFormat             (dsp: *mut FMOD_DSP, channelmask: *mut FMOD_CHANNELMASK, numchannels: *mut ::core::ffi::c_int, source_speakermode: *mut FMOD_SPEAKERMODE) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetOutputChannelFormat       (dsp: *mut FMOD_DSP, inmask: FMOD_CHANNELMASK, inchannels: ::core::ffi::c_int, inspeakermode: FMOD_SPEAKERMODE, outmask: *mut FMOD_CHANNELMASK, outchannels: *mut ::core::ffi::c_int, outspeakermode: *mut FMOD_SPEAKERMODE) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_Reset                        (dsp: *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_SetCallback                  (dsp: *mut FMOD_DSP, callback: FMOD_DSP_CALLBACK) -> FMOD_RESULT;

/*
     DSP parameter control.
*/

pub unsafe fn FMOD_DSP_SetParameterFloat            (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, value: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_SetParameterInt              (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, value: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_SetParameterBool             (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, value: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_SetParameterData             (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, data: *mut ::core::ffi::c_void, length: ::core::ffi::c_uint) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetParameterFloat            (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, value: *mut ::core::ffi::c_float, valuestr: *mut ::core::ffi::c_char, valuestrlen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetParameterInt              (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, value: *mut ::core::ffi::c_int, valuestr: *mut ::core::ffi::c_char, valuestrlen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetParameterBool             (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, value: *mut FMOD_BOOL, valuestr: *mut ::core::ffi::c_char, valuestrlen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetParameterData             (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, data: *mut *mut ::core::ffi::c_void, length: *mut ::core::ffi::c_uint, valuestr: *mut ::core::ffi::c_char, valuestrlen: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetNumParameters             (dsp: *mut FMOD_DSP, numparams: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetParameterInfo             (dsp: *mut FMOD_DSP, index: ::core::ffi::c_int, desc: *mut *mut FMOD_DSP_PARAMETER_DESC) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetDataParameterIndex        (dsp: *mut FMOD_DSP, datatype: ::core::ffi::c_int, index: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_ShowConfigDialog             (dsp: *mut FMOD_DSP, hwnd: *mut ::core::ffi::c_void, show: FMOD_BOOL) -> FMOD_RESULT;

/*
     DSP attributes.
*/

pub unsafe fn FMOD_DSP_GetInfo                      (dsp: *mut FMOD_DSP, name: *mut ::core::ffi::c_char, version: *mut ::core::ffi::c_uint, channels: *mut ::core::ffi::c_int, configwidth: *mut ::core::ffi::c_int, configheight: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetType                      (dsp: *mut FMOD_DSP, r#type: *mut FMOD_DSP_TYPE) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetIdle                      (dsp: *mut FMOD_DSP, idle: *mut FMOD_BOOL) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_DSP_SetUserData                  (dsp: *mut FMOD_DSP, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetUserData                  (dsp: *mut FMOD_DSP, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

/*
     Metering.
*/

pub unsafe fn FMOD_DSP_SetMeteringEnabled           (dsp: *mut FMOD_DSP, inputEnabled: FMOD_BOOL, outputEnabled: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetMeteringEnabled           (dsp: *mut FMOD_DSP, inputEnabled: *mut FMOD_BOOL, outputEnabled: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetMeteringInfo              (dsp: *mut FMOD_DSP, inputInfo: *mut FMOD_DSP_METERING_INFO, outputInfo: *mut FMOD_DSP_METERING_INFO) -> FMOD_RESULT;
pub unsafe fn FMOD_DSP_GetCPUUsage                  (dsp: *mut FMOD_DSP, exclusive: *mut ::core::ffi::c_uint, inclusive: *mut ::core::ffi::c_uint) -> FMOD_RESULT;

/*
    'DSPConnection' API
*/

pub unsafe fn FMOD_DSPConnection_GetInput           (dspconnection: *mut FMOD_DSPCONNECTION, input: *mut *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_DSPConnection_GetOutput          (dspconnection: *mut FMOD_DSPCONNECTION, output: *mut *mut FMOD_DSP) -> FMOD_RESULT;
pub unsafe fn FMOD_DSPConnection_SetMix             (dspconnection: *mut FMOD_DSPCONNECTION, volume: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_DSPConnection_GetMix             (dspconnection: *mut FMOD_DSPCONNECTION, volume: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_DSPConnection_SetMixMatrix       (dspconnection: *mut FMOD_DSPCONNECTION, matrix: *mut ::core::ffi::c_float, outchannels: ::core::ffi::c_int, inchannels: ::core::ffi::c_int, inchannel_hop: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSPConnection_GetMixMatrix       (dspconnection: *mut FMOD_DSPCONNECTION, matrix: *mut ::core::ffi::c_float, outchannels: *mut ::core::ffi::c_int, inchannels: *mut ::core::ffi::c_int, inchannel_hop: ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_DSPConnection_GetType            (dspconnection: *mut FMOD_DSPCONNECTION, r#type: *mut FMOD_DSPCONNECTION_TYPE) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_DSPConnection_SetUserData        (dspconnection: *mut FMOD_DSPCONNECTION, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_DSPConnection_GetUserData        (dspconnection: *mut FMOD_DSPCONNECTION, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

/*
    'Geometry' API
*/

pub unsafe fn FMOD_Geometry_Release                 (geometry: *mut FMOD_GEOMETRY) -> FMOD_RESULT;

/*
     Polygon manipulation.
*/

pub unsafe fn FMOD_Geometry_AddPolygon              (geometry: *mut FMOD_GEOMETRY, directocclusion: ::core::ffi::c_float, reverbocclusion: ::core::ffi::c_float, doublesided: FMOD_BOOL, numvertices: ::core::ffi::c_int, vertices: *const FMOD_VECTOR, polygonindex: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetNumPolygons          (geometry: *mut FMOD_GEOMETRY, numpolygons: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetMaxPolygons          (geometry: *mut FMOD_GEOMETRY, maxpolygons: *mut ::core::ffi::c_int, maxvertices: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetPolygonNumVertices   (geometry: *mut FMOD_GEOMETRY, index: ::core::ffi::c_int, numvertices: *mut ::core::ffi::c_int) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_SetPolygonVertex        (geometry: *mut FMOD_GEOMETRY, index: ::core::ffi::c_int, vertexindex: ::core::ffi::c_int, vertex: *const FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetPolygonVertex        (geometry: *mut FMOD_GEOMETRY, index: ::core::ffi::c_int, vertexindex: ::core::ffi::c_int, vertex: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_SetPolygonAttributes    (geometry: *mut FMOD_GEOMETRY, index: ::core::ffi::c_int, directocclusion: ::core::ffi::c_float, reverbocclusion: ::core::ffi::c_float, doublesided: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetPolygonAttributes    (geometry: *mut FMOD_GEOMETRY, index: ::core::ffi::c_int, directocclusion: *mut ::core::ffi::c_float, reverbocclusion: *mut ::core::ffi::c_float, doublesided: *mut FMOD_BOOL) -> FMOD_RESULT;

/*
     Object manipulation.
*/

pub unsafe fn FMOD_Geometry_SetActive               (geometry: *mut FMOD_GEOMETRY, active: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetActive               (geometry: *mut FMOD_GEOMETRY, active: *mut FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_SetRotation             (geometry: *mut FMOD_GEOMETRY, forward: *const FMOD_VECTOR, up: *const FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetRotation             (geometry: *mut FMOD_GEOMETRY, forward: *mut FMOD_VECTOR, up: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_SetPosition             (geometry: *mut FMOD_GEOMETRY, position: *const FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetPosition             (geometry: *mut FMOD_GEOMETRY, position: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_SetScale                (geometry: *mut FMOD_GEOMETRY, scale: *const FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetScale                (geometry: *mut FMOD_GEOMETRY, scale: *mut FMOD_VECTOR) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_Save                    (geometry: *mut FMOD_GEOMETRY, data: *mut ::core::ffi::c_void, datasize: *mut ::core::ffi::c_int) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_Geometry_SetUserData             (geometry: *mut FMOD_GEOMETRY, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_Geometry_GetUserData             (geometry: *mut FMOD_GEOMETRY, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;

/*
    'Reverb3D' API
*/

pub unsafe fn FMOD_Reverb3D_Release                 (reverb3d: *mut FMOD_REVERB3D) -> FMOD_RESULT;

/*
     Reverb manipulation.
*/

pub unsafe fn FMOD_Reverb3D_Set3DAttributes         (reverb3d: *mut FMOD_REVERB3D, position: *const FMOD_VECTOR, mindistance: ::core::ffi::c_float, maxdistance: ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Reverb3D_Get3DAttributes         (reverb3d: *mut FMOD_REVERB3D, position: *mut FMOD_VECTOR, mindistance: *mut ::core::ffi::c_float, maxdistance: *mut ::core::ffi::c_float) -> FMOD_RESULT;
pub unsafe fn FMOD_Reverb3D_SetProperties           (reverb3d: *mut FMOD_REVERB3D, properties: *const FMOD_REVERB_PROPERTIES) -> FMOD_RESULT;
pub unsafe fn FMOD_Reverb3D_GetProperties           (reverb3d: *mut FMOD_REVERB3D, properties: *mut FMOD_REVERB_PROPERTIES) -> FMOD_RESULT;
pub unsafe fn FMOD_Reverb3D_SetActive               (reverb3d: *mut FMOD_REVERB3D, active: FMOD_BOOL) -> FMOD_RESULT;
pub unsafe fn FMOD_Reverb3D_GetActive               (reverb3d: *mut FMOD_REVERB3D, active: *mut FMOD_BOOL) -> FMOD_RESULT;

/*
     Userdata set/get.
*/

pub unsafe fn FMOD_Reverb3D_SetUserData             (reverb3d: *mut FMOD_REVERB3D, userdata: *mut ::core::ffi::c_void) -> FMOD_RESULT;
pub unsafe fn FMOD_Reverb3D_GetUserData             (reverb3d: *mut FMOD_REVERB3D, userdata: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT;
}
