// @generated by carcinize.nu from FMOD headers
/* ======================================================================================== */
/* FMOD Core API - output development header file.                                          */
/* Copyright (c), Firelight Technologies Pty, Ltd. 2004-2025.                               */
/*                                                                                          */
/* Use this header if you are wanting to develop your own output plugin to use with         */
/* FMOD's output system.  With this header you can make your own output plugin that FMOD    */
/* can register and use.  See the documentation and examples on how to make a working       */
/* plugin.                                                                                  */
/*                                                                                          */
/* For more detail visit:                                                                   */
/* https://fmod.com/docs/2.03/api/plugin-api-output.html                                    */
/* ======================================================================================== */


/*
    Output constants
*/
pub const FMOD_OUTPUT_PLUGIN_VERSION: ::core::ffi::c_int = 5;

pub const FMOD_OUTPUT_METHOD_MIX_DIRECT:    FMOD_OUTPUT_METHOD = 0;
pub const FMOD_OUTPUT_METHOD_MIX_BUFFERED:  FMOD_OUTPUT_METHOD = 1;
pub type FMOD_OUTPUT_METHOD = ::core::ffi::c_uint;

/*
    Output callbacks
*/
pub type FMOD_OUTPUT_GETNUMDRIVERS_CALLBACK     = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, numdrivers: *mut ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_GETDRIVERINFO_CALLBACK     = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, id: ::core::ffi::c_int, name: *mut ::core::ffi::c_char, namelen: ::core::ffi::c_int, guid: *mut FMOD_GUID, systemrate: *mut ::core::ffi::c_int, speakermode: *mut FMOD_SPEAKERMODE, speakermodechannels: *mut ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_INIT_CALLBACK              = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, selecteddriver: ::core::ffi::c_int, flags: FMOD_INITFLAGS, outputrate: *mut ::core::ffi::c_int, speakermode: *mut FMOD_SPEAKERMODE, speakermodechannels: *mut ::core::ffi::c_int, outputformat: *mut FMOD_SOUND_FORMAT, dspbufferlength: ::core::ffi::c_int, dspnumbuffers: *mut ::core::ffi::c_int, dspnumadditionalbuffers: *mut ::core::ffi::c_int, extradriverdata: *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_START_CALLBACK             = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_STOP_CALLBACK              = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_CLOSE_CALLBACK             = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_UPDATE_CALLBACK            = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_GETHANDLE_CALLBACK         = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, handle: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_MIXER_CALLBACK             = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_OBJECT3DGETINFO_CALLBACK   = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, maxhardwareobjects: *mut ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_OBJECT3DALLOC_CALLBACK     = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, object3d: *mut *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_OBJECT3DFREE_CALLBACK      = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, object3d: *mut ::core::ffi::c_void) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_OBJECT3DUPDATE_CALLBACK    = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, object3d: *mut ::core::ffi::c_void, info: *const FMOD_OUTPUT_OBJECT3DINFO) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_OPENPORT_CALLBACK          = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, portType: FMOD_PORT_TYPE, portIndex: FMOD_PORT_INDEX, portId: *mut ::core::ffi::c_int, portRate: *mut ::core::ffi::c_int, portChannels: *mut ::core::ffi::c_int, portFormat: *mut FMOD_SOUND_FORMAT) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_CLOSEPORT_CALLBACK         = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, portId: ::core::ffi::c_int) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_DEVICELISTCHANGED_CALLBACK = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE) -> FMOD_RESULT>;

/*
    Output functions
*/
pub type FMOD_OUTPUT_READFROMMIXER_FUNC         = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, buffer: *mut ::core::ffi::c_void, length: ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_COPYPORT_FUNC              = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE, portId: ::core::ffi::c_int, buffer: *mut ::core::ffi::c_void, length: ::core::ffi::c_uint) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_REQUESTRESET_FUNC          = Option<unsafe extern "system" fn (output_state: *mut FMOD_OUTPUT_STATE) -> FMOD_RESULT>;
pub type FMOD_OUTPUT_ALLOC_FUNC                 = Option<unsafe extern "system" fn (size: ::core::ffi::c_uint, align: ::core::ffi::c_uint, file: *const ::core::ffi::c_char, line: ::core::ffi::c_int) -> *mut ::core::ffi::c_void      >;
pub type FMOD_OUTPUT_FREE_FUNC                  = Option<unsafe extern "system" fn (ptr: *mut ::core::ffi::c_void, file: *const ::core::ffi::c_char, line: ::core::ffi::c_int)>;
pub type FMOD_OUTPUT_LOG_FUNC                   = unsafe extern "C" fn (level: FMOD_DEBUG_FLAGS, file: *const ::core::ffi::c_char, line: ::core::ffi::c_int, function: *const ::core::ffi::c_char, string: *const ::core::ffi::c_char, ...);

/*
    Output structures
*/
#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_OUTPUT_DESCRIPTION {
    pub apiversion: ::core::ffi::c_uint,
    pub name: *const ::core::ffi::c_char,
    pub version: ::core::ffi::c_uint,
    pub method: FMOD_OUTPUT_METHOD,
    pub getnumdrivers: FMOD_OUTPUT_GETNUMDRIVERS_CALLBACK,
    pub getdriverinfo: FMOD_OUTPUT_GETDRIVERINFO_CALLBACK,
    pub init: FMOD_OUTPUT_INIT_CALLBACK,
    pub start: FMOD_OUTPUT_START_CALLBACK,
    pub stop: FMOD_OUTPUT_STOP_CALLBACK,
    pub close: FMOD_OUTPUT_CLOSE_CALLBACK,
    pub update: FMOD_OUTPUT_UPDATE_CALLBACK,
    pub gethandle: FMOD_OUTPUT_GETHANDLE_CALLBACK,
    pub mixer: FMOD_OUTPUT_MIXER_CALLBACK,
    pub object3dgetinfo: FMOD_OUTPUT_OBJECT3DGETINFO_CALLBACK,
    pub object3dalloc: FMOD_OUTPUT_OBJECT3DALLOC_CALLBACK,
    pub object3dfree: FMOD_OUTPUT_OBJECT3DFREE_CALLBACK,
    pub object3dupdate: FMOD_OUTPUT_OBJECT3DUPDATE_CALLBACK,
    pub openport: FMOD_OUTPUT_OPENPORT_CALLBACK,
    pub closeport: FMOD_OUTPUT_CLOSEPORT_CALLBACK,
    pub devicelistchanged: FMOD_OUTPUT_DEVICELISTCHANGED_CALLBACK,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_OUTPUT_STATE {
    pub plugindata: *mut ::core::ffi::c_void,
    pub readfrommixer: FMOD_OUTPUT_READFROMMIXER_FUNC,
    pub alloc: FMOD_OUTPUT_ALLOC_FUNC,
    pub free: FMOD_OUTPUT_FREE_FUNC,
    pub log: FMOD_OUTPUT_LOG_FUNC,
    pub copyport: FMOD_OUTPUT_COPYPORT_FUNC,
    pub requestreset: FMOD_OUTPUT_REQUESTRESET_FUNC,
}

#[repr(C)] #[derive(Copy, Clone)] pub struct FMOD_OUTPUT_OBJECT3DINFO {
    pub buffer: *mut ::core::ffi::c_float,
    pub bufferlength: ::core::ffi::c_uint,
    pub position: FMOD_VECTOR,
    pub gain: ::core::ffi::c_float,
    pub spread: ::core::ffi::c_float,
    pub priority: ::core::ffi::c_float,
}

/*
    Output macros
*/
